/* Direct recorded-data analysis. Validate internally, then render; no confirmation form. */
(function(g){'use strict';
const clone=x=>JSON.parse(JSON.stringify(x)),esc=x=>String(x??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const norm=s=>String(s||'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/[^a-z0-9]/g,'');
function normalizeFollowup(q){return String(q||'').replace(/(^|\s)(\d+)\s*(경기|그랑프리)(?=로|\s*(?:바꿔|변경))/g,'$1최근 $2$3').replace(/(?:change (?:it )?to|make it)\s+(\d+)\s+(matches|races)/gi,'recent $1 $2');}
function review({form,input,status,out,prepare,validate=p=>p,execute,render,summarize,onCommit,en=false}){
 const panel=document.createElement('section');panel.className='ml-query-clarify';panel.hidden=true;form.after(panel);let previous=null,version=0;
 const tr=(a,b)=>en?b:a;
 function clear(){version++;previous=null;panel.hidden=true;panel.replaceChildren();input.value='';out.replaceChildren();status.textContent=tr('새 질문을 입력해 주세요.','Enter a new question.');input.focus();onCommit?.(null);}
 function message(error){const messages={
 metric_required:['분석할 지표를 질문에 적어 주세요.','Include a metric in your question.'],
 ambiguous:['비교할 지표를 골라 주세요.','Choose a metric to compare.'],context:['먼저 분석을 실행한 뒤 조건을 바꿔 주세요.','Run an analysis before asking a follow-up.'],range:['보유한 연도와 경기 수 범위를 확인해 주세요.','Check the available years and race count.'],too_many:['비교 대상과 지표는 각각 최대 4개입니다.','Select at most four subjects and four metrics.'],future:['아직 종료 기록이 없습니다. 예측 지표를 선택해 주세요.','No completed records yet. Choose a prediction metric.'],no_data:['선택한 기간·대상의 해당 지표가 미확보입니다. 다른 지표나 기간을 선택해 주세요.','This metric is not recorded for the selected period and subjects. Choose another metric or period.'],no_match:['조건에 맞는 기록이 없습니다. 수치 조건을 완화해 주세요.','No records match the filters. Relax the value conditions.'],team:['구단 이름을 적거나, 리그 전체 순위를 질문해 주세요.','Name a club or ask for a league ranking.'],league_mismatch:['리그와 구단이 일치하지 않습니다. 구단을 다시 선택해 주세요.','The league and clubs do not match. Choose clubs again.'],season:['확보한 시즌을 선택해 주세요.','Choose a recorded season.'],metric:['이 질문의 지표는 아직 지원하지 않습니다. 기대 득점·득점·실점·승점·승률을 조회할 수 있습니다.','That metric is not supported yet. Ask for expected goals, goals, points or win rate.'],drivers:['선택한 기간에 참가한 드라이버를 골라 주세요.','Choose drivers who participated in this period.'],conditions:['지표와 추가 조건이 맞지 않습니다. 조건을 지우거나 지표를 바꿔 주세요.','The metric and extra conditions do not match. Clear the filters or change the metric.'],unsupported:['조건을 해석하지 못했습니다. 대상·기간·지표를 구체적으로 적어 주세요.','Could not interpret these conditions. Specify a subject, period and supported metric.']};return (messages[error]||messages.unsupported)[en?1:0];}
 function clarify(question){panel.hidden=false;panel.innerHTML=`<h4>${tr('어떤 기준으로 볼까요?','Which metric would you like?')}</h4><div class="ml-query-choices">${(prepare.sport==='football'?[['승점','Points'],['승률','Win rate'],['기대 득점','Expected goals']]:[['포인트','Points'],['최종 순위','Final position'],['평균 랩타임','Mean lap time']]).map(([ko,english])=>`<button type="button" data-clarify="${esc(en?english:ko)}">${esc(en?english:ko)}</button>`).join('')}</div>`;panel.querySelectorAll('[data-clarify]').forEach(b=>b.onclick=()=>{input.value=question.replace(/잘한|잘하는|좋은|좋았던|best|better|good/gi,'')+' '+b.dataset.clarify+' '+(en?'ranking':'순위');request(input.value);});status.textContent=message('ambiguous');}
 function stage(plan){panel.hidden=true;panel.replaceChildren();out.replaceChildren();try{
  if(!plan||plan.error){status.textContent=message(plan?.error||'unsupported');return {error:plan?.error||'unsupported'};}
  const checked=validate(clone(plan));if(checked.error){status.textContent=message(checked.error);return checked;}
  const result=execute(checked);if(!result||result.error){status.textContent=message(result?.error||'no_data');return result;}
  render(result,checked);const context=document.createElement('div');context.className='ml-analysis-context';context.innerHTML=`<p aria-label="${tr('적용된 조건','Applied conditions')}">${esc(summarize(checked,result))}</p><button type="button" data-query-reset>${tr('새 질문','New question')}</button>`;out.prepend(context);context.querySelector('button').onclick=clear;
  previous=clone(checked);onCommit?.(checked);status.textContent=tr('분석했습니다. 이어서 기간이나 지표를 바꿔 질문할 수 있습니다.','Analysis complete. Ask a follow-up to change the period or metric.');return result;
 }catch{out.replaceChildren();status.textContent=message('unsupported');return {error:'unsupported'};}}
 async function request(question,remote){const ticket=++version;panel.hidden=true;panel.replaceChildren();out.replaceChildren();if(typeof question!=='string'||!question.trim()||question.length>500){status.textContent=message('unsupported');return {error:'unsupported'};}
 const vague=/잘한|잘하는|좋은|좋았던|\b(?:better|good|best (?:teams?|drivers?))\b/i.test(question),hasMetric=prepare.hasMetric?.(question);
 if(vague&&!hasMetric){clarify(question);return {clarification:true};}
 const clean=vague?question.replace(/잘한|잘하는|좋은|좋았던|\b(?:better|good|best)\b/gi,''):question;
 status.textContent=tr('기록을 분석하고 있습니다.','Analyzing recorded data.');
 if(remote){try{const p=await remote(previous);if(ticket!==version)return;return stage(p);}catch{if(ticket===version)status.textContent=tr('AI 연결에 실패했습니다. 저장 기록 분석으로 다시 시도해 주세요.','AI connection failed. Try stored-record analysis.');return {error:'provider'};}}
 return stage(prepare(clean,previous));
 }
 return {request,stage,clear,cancelDraft(){version++;panel.hidden=true;panel.replaceChildren();out.replaceChildren();},get previous(){return previous;},destroy(){version++;panel.remove();}};
}
function football({form,input,status,out,engine,data,defaults,render,onCommit,en=false}){
 const tr=(a,b)=>en?b:a,metrics=g.MatchDeskAnalysis.metrics;
 const prepare=(q,prev)=>engine.parse(normalizeFollowup(q),defaults(),prev);prepare.sport='football';prepare.hasMetric=q=>Object.values(metrics).some(m=>m.keys.some(k=>q.toLowerCase().includes(k)));
 function validate(p){if(!['team','comparison','ranking','venue','trend'].includes(p.tool))return {error:'unsupported'};if(!metrics[p.metric]||!['EPL','La_liga'].includes(p.league)||!['all','home','away'].includes(p.venue))return {error:'unsupported'};if(!Array.isArray(p.teams)||p.teams.length>4)return {error:'too_many'};if(p.teams.some(id=>!data.teams[id]||data.teams[id].league!==p.league))return {error:'league_mismatch'};if(p.tool!=='ranking'&&!p.teams.length)return {error:'team'};if(!data.completed.some(m=>m.season===p.season&&m.league===p.league))return {error:'season'};if(p.last!==null&&p.last!==undefined&&(!Number.isInteger(p.last)||p.last<1||p.last>38))return {error:'range'};return p;}
 function summarize(p){return [(p.tool==='ranking'?tr('전체 구단','All clubs'):p.teams.map(id=>data.teams[id].name).join(', ')),p.league==='EPL'?'Premier League':'LaLiga',p.season,p.last?tr('최근 '+p.last+'경기','Last '+p.last+' matches'):tr('시즌 전체','Full season'),p.tool==='venue'?tr('홈·원정 비교','Home / away'):p.venue==='all'?'':tr(p.venue==='home'?'홈':'원정',p.venue),metrics[p.metric][en?'en':'ko']+(p.compareGoals?tr(' / 실제 득점',' / actual goals'):''),p.metric==='w'?'%':p.perMatch?tr('경기당 평균','Per-match average'):tr('합계','Total')].filter(Boolean).join(' · ');}
 return review({form,input,status,out,prepare,validate,summarize,execute:p=>{const r=engine.execute(p);return r.status==='ok'?r:{error:r.status==='empty'?'no_data':r.reason||'unsupported'};},render,onCommit,en});
}
function f1Planner({race,prediction,history,core,legacy}){
 const currentYear=Number(race.session.year||race.session.date_start.slice(0,4)),cutoff=Date.parse(race.session.date_start),catalogue=[...new Map([...(history?.races||[]),race].map(r=>[r.session.session_key,r])).values()];
 const roster=[...new Map(catalogue.flatMap(r=>(r.records?.drivers||[])).concat(prediction?.drivers||[]).map(d=>[norm(d.full_name||d.name),{...d,full_name:d.full_name||d.name}])).values()];
 const synthetic={...race,state:'completed',records:{drivers:roster.map((d,i)=>({...d,driver_number:i+1000}))}};
 const nameOf=n=>synthetic.records.drivers.find(d=>d.driver_number===n)?.full_name;
 function periodRaces(p){if(p.period.mode==='gp'){if(p.period.sessionKey){const target=catalogue.find(r=>String(r.session.session_key)===String(p.period.sessionKey)&&Number(r.session.year||r.session.date_start.slice(0,4))===p.period.year);return target?[target]:[];}if(p.period.year===currentYear)return [race];const scope=g.MatchLabF1History.select(p.period.year+' records',race,history);return scope.selected.map(s=>s.race);}const all=catalogue.filter(r=>r.state==='completed'&&r.session.session_name==='Race'&&Number(r.session.year||r.session.date_start.slice(0,4))===p.period.year&&Date.parse(r.session.date_start)<=cutoff).sort((a,b)=>Date.parse(a.session.date_start)-Date.parse(b.session.date_start)||a.session.session_key-b.session.session_key);return all.slice(-p.period.count);}
 function prepare(q,previous){q=normalizeFollowup(q);
  if(!q.trim()||q.length>500)return {error:'unsupported'};
  const manyYears=[...q.matchAll(/\b20\d{2}\b/g)].length>1,overview=/기록|성적|records|results/i.test(q)&&/작년|재작년|20\d{2}|last year/i.test(q);
  if((manyYears||overview)&&legacy){const p=legacy.parse(q.replace(/\bin\s+(?=20\d{2}\b)/gi,''),race,prediction,previous?.legacyPlan,history);return p.error?p:{legacyPlan:p,kind:'legacy'};}
  let text=q,year=null,count=null;const recent=text.match(/(?:최근|last|recent)\s*(\d+)\s*(?:경기|그랑프리|gp|races?)/i);if(recent){count=Number(recent[1]);text=text.replace(recent[0],' ');if(count<1||count>24)return {error:'range'};}
  const explicit=text.match(/\b(20\d{2})\s*년?/);if(explicit){year=Number(explicit[1]);text=text.replace(explicit[0],' ');}else if(/재작년|year before last/i.test(text)){year=currentYear-2;text=text.replace(/재작년|year before last/gi,' ');}else if(/작년|지난\s*시즌|last year|previous year/i.test(text)){year=currentYear-1;text=text.replace(/작년|지난\s*시즌|last year|previous year/gi,' ');}else if(/올해|이번\s*시즌|this year/i.test(text)){year=currentYear;text=text.replace(/올해|이번\s*시즌|this year/gi,' ');}
  if(year!==null&&(year<2024||year>currentYear))return {error:'range'};
  const followWords=/추가|더해|바꿔|변경|대신|반대로|역순|제거|빼\s*줘|add|replace|change|instead|reverse|remove/i,follow=!!previous&&previous.kind!=='legacy'&&(followWords.test(text)||count!==null||year!==null);
  if(followWords.test(text)&&!previous)return {error:'context'};
  const add=/추가|더해|\badd\b/i.test(text),remove=/제거|빼\s*줘|\bremove\b/i.test(text),reverse=/반대로|역순|reverse/i.test(text);
  text=text.replace(/추가(?:해\s*줘(?:요)?)?|더해(?:\s*줘)?|바꿔(?:\s*줘(?:요)?)?|변경(?:해\s*줘)?|대신|제거(?:해\s*줘)?|빼\s*줘|해\s*줘(?:요)?|(?:으로|로)(?=\s|$)|\b(?:add|replace|change|instead|remove|to|in|with)\b/gi,' ');
  const prior=follow?clone(previous):null;if(prior){text=text.replace(/반대로|역순|reverse|opposite/gi,' ');}
  let parsed=core.parse(text,synthetic,prediction);if(prior&&(parsed.error==='unsupported'||(parsed.error==='question'&&!text.trim()))){parsed=core.parse(text+' '+prior.metrics.map(k=>k==='laps'?'랩타임 변화':g.MatchLabF1Metrics.registry[k]?.ko).join(' '),synthetic,prediction);}
  if(parsed.error)return parsed;
  let driverNames=parsed.drivers.map(nameOf);if(prior){if(add)driverNames=[...new Set([...prior.driverNames,...driverNames])];else if(remove)driverNames=prior.driverNames.filter(n=>!driverNames.some(x=>norm(x)===norm(n)));else if(!driverNames.length)driverNames=prior.driverNames;}
  if(driverNames.length>4||parsed.metrics.length>4)return {error:'too_many'};
  const p={kind:'f1',driverNames,metrics:parsed.metrics,metric:parsed.metric,conditions:prior?{...prior.conditions,...parsed.conditions}:parsed.conditions,period:prior?prior.period:{mode:'gp',year:currentYear,count:5},aggregation:prior?.aggregation||'auto',follow,session_key:race.session.session_key};
  if(count!==null)p.period={...p.period,mode:'recent',count};if(year!==null){p.period.year=year;delete p.period.sessionKey;}
  if(reverse){const low=['mean_lap','best_lap','final_position','expected_rank','mean_stop','mean_pit_lane'].includes(p.metric);p.conditions.order=(p.conditions.order||(low?'asc':'desc'))==='asc'?'desc':'asc';}
  if(prior&&JSON.stringify(parsed.metrics)!==JSON.stringify(prior.metrics))p.aggregation='auto';if(/평균|경기당|average|mean/i.test(q))p.aggregation='mean';
  return validate(p);
 }
 function validate(p){if(p.kind==='legacy')return p;if(p.session_key!==race.session.session_key||!['gp','recent'].includes(p.period.mode)||!Number.isInteger(p.period.year)||p.period.year<2024||p.period.year>currentYear||!Number.isInteger(p.period.count)||p.period.count<1||p.period.count>24)return {error:'range'};if(p.driverNames.length>4||p.metrics.length>4)return {error:'too_many'};if(p.metrics.some(k=>!core.queryKeys.includes(k)&&k!=='laps'))return {error:'unsupported'};const numeric=['laps','final_status'];if((p.conditions.threshold||p.conditions.limit||p.conditions.order)&&(p.metrics.length!==1||numeric.includes(p.metric)))return {error:'unsupported'};if((p.conditions.from||p.conditions.excludePit)&&p.metrics.some(k=>!['laps','best_lap','mean_lap','valid_laps','lap_std','sector_1','sector_2','sector_3','top_speed'].includes(k)))return {error:'unsupported'};if(p.conditions.threshold?.unit){const u=p.conditions.threshold.unit;if(/초|seconds?|^s$/.test(u)&&!['best_lap','mean_lap','lap_std','sector_1','sector_2','sector_3','mean_stop','mean_pit_lane'].includes(p.metric))return {error:'unsupported'};if(/km|킬로/.test(u)&&p.metric!=='top_speed')return {error:'unsupported'};if(u==='%'&&p.metric!=='win_probability')return {error:'unsupported'};if(/포인트|점|points?/.test(u)&&!['points','recent5_points'].includes(p.metric))return {error:'unsupported'};}if(p.period.mode==='recent'&&p.metrics.some(k=>k==='laps'||k==='final_status'||g.MatchLabF1Metrics.registry[k]?.category==='prediction'))return {error:'unsupported'};return p;}
 function execute(p){const checked=validate(p);if(checked.error)return checked;if(p.kind==='legacy')return {kind:'legacy',result:legacy.execute(p.legacyPlan,race,prediction,history)};const selected=periodRaces(p);if(!selected.length)return {error:'no_data'};const ids=new Set(rosterFor(p).map(d=>norm(d.full_name)));if(p.driverNames.some(n=>!ids.has(norm(n))))return {error:'drivers'};if(p.metrics.some(k=>!metricsFor(p).includes(k)))return {error:'no_data'};const results=[];
  for(const r of selected){const ds=r.state==='completed'?(r.records?.drivers||[]):(prediction?.drivers||[]),numbers=ds.filter(d=>p.driverNames.some(n=>norm(n)===norm(d.full_name||d.name))).map(d=>d.driver_number);if(p.driverNames.length&&!numbers.length)continue;const plan={metric:p.metric,metrics:p.metrics,drivers:numbers,conditions:p.period.mode==='recent'?{from:p.conditions.from,to:p.conditions.to,excludePit:p.conditions.excludePit}:p.conditions,session_key:r.session.session_key};if(r.state!=='completed'&&p.metrics.some(k=>g.MatchLabF1Metrics.registry[k]?.category!=='prediction'))return {error:'future'};results.push({race:r,result:core.execute(plan,r,r===race?prediction:history?.predictions?.[String(r.session.session_key)])});}
  if(!results.length)return {error:'no_data'};if(p.period.mode==='gp'){const result=results[0].result;const parts=result.kind==='multiple'?result.results:[result];if(parts.every(x=>!x.rows?.length))return {error:'no_match'};return {kind:'single',result,races:selected,plan:p};}
  const names=p.driverNames.length?p.driverNames:[...new Map(results.flatMap(x=>x.result.rows||x.result.results?.flatMap(y=>y.rows)||[]).map(r=>[norm(r.name),r.name])).values()];
  const summaries=p.metrics.map(metric=>{let rows=names.map(name=>{const samples=results.map(x=>({race:x.race,row:(x.result.kind==='multiple'?x.result.results.find(z=>z.metric===metric):x.result)?.rows?.find(z=>norm(z.name)===norm(name))})).filter(x=>typeof x.row?.value==='number'&&Number.isFinite(x.row.value));const values=samples.map(x=>x.row.value);const method=p.aggregation==='mean'?'mean':['points','completed_laps','valid_laps','pit_entries','stint_count'].includes(metric)?'sum':metric==='best_lap'?'min':metric==='top_speed'?'max':'mean';const value=!values.length?null:method==='sum'?values.reduce((a,b)=>a+b,0):method==='min'?Math.min(...values):method==='max'?Math.max(...values):values.reduce((a,b)=>a+b,0)/values.length;return {name,value,recorded:values.length,method,dates:samples.map(x=>x.race.session.date_start.slice(0,10))};});
   if(p.conditions.threshold){const t=p.conditions.threshold;rows=rows.filter(r=>r.value!==null&&({lt:r.value<t.value,lte:r.value<=t.value,gt:r.value>t.value,gte:r.value>=t.value})[t.op]);}const low=['mean_lap','best_lap','final_position','mean_stop','mean_pit_lane','lap_std','sector_1','sector_2','sector_3'].includes(metric);rows.sort((a,b)=>a.value===null?1:b.value===null?-1:(a.value-b.value)*((p.conditions.order|| (low?'asc':'desc'))==='asc'?1:-1));if(p.conditions.limit)rows=rows.slice(0,p.conditions.limit);const unit=results.map(x=>x.result.kind==='multiple'?x.result.results.find(z=>z.metric===metric):x.result).find(Boolean)?.unit||'';return {kind:'bar',metric,unit,rows};});return {kind:'recent',result:summaries.length===1?summaries[0]:{kind:'multiple',results:summaries},races:selected,plan:p};
 }
 const coverageCache=new Map();
 function predictionFor(r){return r.session.session_key===race.session.session_key?prediction:history?.predictions?.[String(r.session.session_key)];}
 function racesForYear(y){return catalogue.filter(r=>Number(r.session.year||r.session.date_start.slice(0,4))===y&&r.session.session_name==='Race'&&(r.state==='completed'||r.session.session_key===race.session.session_key)).sort((a,b)=>Date.parse(a.session.date_start)-Date.parse(b.session.date_start));}
 function rosterFor(p){return [...new Map(periodRaces(p).flatMap(r=>r.state==='completed'?(r.records?.drivers||[]):(predictionFor(r)?.drivers||[])).map(d=>[norm(d.full_name||d.name),{...d,full_name:d.full_name||d.name}])).values()].sort((a,b)=>a.full_name.localeCompare(b.full_name));}
 function metricsFor(p){const available=new Set();for(const r of periodRaces(p)){
 const cacheKey=String(r.session.session_key);if(!coverageCache.has(cacheKey)){const entries=new Map();for(const d of r.records?.drivers||predictionFor(r)?.drivers||[]){const keys=g.MatchLabF1Metrics.calculate(r,d.driver_number,predictionFor(r)).filter(m=>m.value!==null&&m.value!==undefined&&(typeof m.value!=='number'||Number.isFinite(m.value))).map(m=>m.key);if(r.records?.laps?.some(l=>l.driver_number===d.driver_number&&Number.isFinite(l.lap_duration)&&l.lap_duration>0))keys.push('laps');entries.set(norm(d.full_name||d.name),keys);}coverageCache.set(cacheKey,entries);}
 for(const [name,keys] of coverageCache.get(cacheKey)){if(p.driverNames.length&&!p.driverNames.some(n=>norm(n)===name))continue;for(const k of keys){if(p.period.mode==='recent'&&(k==='laps'||k==='final_status'||g.MatchLabF1Metrics.registry[k]?.category==='prediction'))continue;if(r.state!=='completed'&&g.MatchLabF1Metrics.registry[k]?.category!=='prediction')continue;available.add(k);}}
 }return [...core.queryKeys,'laps'].filter(k=>available.has(k));}
 return {prepare,execute,validate,roster,currentYear,periodRaces,rosterFor,metricsFor,racesForYear,years:[...new Set(catalogue.map(r=>Number(r.session.year||r.session.date_start.slice(0,4))))].sort()};
}
function f1({host,race,prediction,history,core,legacy,locale='ko'}){const en=locale==='en',tr=(a,b)=>en?b:a,planner=f1Planner({race,prediction,history,core,legacy});planner.prepare.sport='f1';planner.prepare.hasMetric=q=>[...core.queryKeys].some(k=>{const m=g.MatchLabF1Metrics.registry[k];return q.toLowerCase().includes(k)||[m?.ko,m?.en].some(n=>n&&q.toLowerCase().includes(n.toLowerCase()));})||/포인트|랩타임|points|lap time|순위|position/i.test(q);
 function summarize(p,r){if(p.kind==='legacy')return [p.legacyPlan.years?.join(', '),tr('같은 GP의 과거 기록','Historical records for the same GP')].filter(Boolean).join(' · ');return [p.driverNames.length?p.driverNames.map(n=>g.MatchLabF1Names.display(n,en)).join(', '):tr('전체 드라이버','All drivers'),p.period.year,p.period.mode==='recent'?tr('최근 '+p.period.count+' GP','Last '+p.period.count+' GPs'):(r.races?.[0]?.meeting?.meeting_name||race.meeting?.meeting_name),p.metrics.map(k=>k==='laps'?tr('랩타임 변화','Lap-time trend'):g.MatchLabF1Metrics.registry[k][en?'en':'ko']).join(', '),p.period.mode==='recent'&&p.aggregation==='mean'?tr('GP별 평균','Mean per GP'):'',p.conditions.from?tr(p.conditions.from+'–'+p.conditions.to+'랩','Laps '+p.conditions.from+'–'+p.conditions.to):'',p.conditions.excludePit?tr('피트랩 제외','Pit laps excluded'):'',p.conditions.threshold?({lt:'<',lte:'≤',gt:'>',gte:'≥'}[p.conditions.threshold.op]+' '+p.conditions.threshold.value+' '+(p.conditions.threshold.unit||'')):'',p.conditions.limit?tr('상위 '+p.conditions.limit+'명','Top '+p.conditions.limit):''].filter(Boolean).join(' · ');}
 return review({form:host.querySelector('form'),input:host.querySelector('textarea'),status:host.querySelector('.nl-status'),out:host.querySelector('.nl-output'),prepare:planner.prepare,validate:planner.validate,summarize,execute:planner.execute,
render:(r,p)=>{const out=host.querySelector('.nl-output');if(r.kind==='legacy'){out.innerHTML=legacy.draw(r.result,en);return;}out.innerHTML=(r.kind==='recent'?`<p>${tr('확보한 종료 GP','Collected completed GPs')}: ${r.races.length}/${p.period.count} · ${esc(r.races[0].session.date_start.slice(0,10))}–${esc(r.races.at(-1).session.date_start.slice(0,10))}</p>`:'')+core.draw(r.result,en)+(r.kind==='recent'?`<p>${tr('지표가 미확보인 GP는 해당 지표 계산에서 제외합니다.','GPs with missing values are excluded from that metric.')}</p><div class="ml-plan-coverage">${(r.result.kind==='multiple'?r.result.results:[r.result]).flatMap(x=>x.rows.map(row=>`<p>${esc(g.MatchLabF1Names.display(row.name,en))}: ${row.recorded} ${tr('경기 기록','recorded GPs')} · ${esc(en?row.method:({sum:'합계',mean:'GP별 값의 평균',min:'최솟값',max:'최댓값'}[row.method]||row.method))}</p>`)).join('')}</div>`:'');},en});
}
const api={football,f1,f1Planner};g.MatchLabAnalysisWorkbench=api;if(typeof module!=='undefined'&&module.exports)module.exports=api;
if(typeof document!=='undefined'){const s=document.createElement('style');s.id='ml-query-styles';s.textContent=`.ml-analysis-context{display:flex;align-items:center;justify-content:space-between;gap:12px;flex-wrap:wrap;border-bottom:1px solid #c6d4db;padding:8px 0;margin-bottom:16px;font:14px/1.6 Arial,'Malgun Gothic',sans-serif;color:#365361}.ml-analysis-context p{margin:0;flex:1;min-width:min(100%,200px);overflow-wrap:anywhere}.ml-analysis-context button,.ml-query-choices button{min-height:44px;border:1px solid #98acb5;border-radius:8px;background:#fff;color:#16384c;padding:8px 12px;font:inherit;cursor:pointer}.ml-query-clarify{padding:14px 0;min-width:0;font:16px/1.6 Arial,'Malgun Gothic',sans-serif}.ml-query-clarify[hidden]{display:none}.ml-query-clarify h4{margin:0 0 8px}.ml-query-choices{display:flex;gap:8px;flex-wrap:wrap}.ml-query-clarify button:focus-visible,.ml-analysis-context button:focus-visible{outline:3px solid #1186ac;outline-offset:2px}.ml-plan-coverage{font-size:14px}`;(document.head||document.documentElement).append(s);}
})(globalThis);
