const {chromium}=require('playwright'),fs=require('node:fs'),assert=require('node:assert/strict');
const {createServer}=require('../../server/gemini.cjs');
(async()=>{const server=createServer({key:''});await new Promise(r=>server.listen(0,'127.0.0.1',r));const base='http://127.0.0.1:'+server.address().port;
const browser=await chromium.launch({executablePath:'C:/Program Files (x86)/Microsoft/Edge/Application/msedge.exe',headless:true});const checks=[];
try{const p=await browser.newPage();const errors=[];p.on('pageerror',e=>errors.push(e.message));
for(const lang of ['ko','en']){await p.goto(base+'/f1/index.html?year=2026&lang='+lang);const card=p.locator('#catalog .card').filter({hasText:'Bahrain GP in Malaysia'});assert.equal(await card.count(),1);assert.equal((await card.innerText()).includes('바레인'),false);await card.locator('[data-race]').click();assert((await p.locator('.detail-head h2').innerText()).includes('Bahrain GP in Malaysia'));checks.push({lang,title:'Bahrain GP in Malaysia'});
for(const width of [390,768,1440]){await p.setViewportSize({width,height:900});await p.goto(base+'/f1/index.html?year=2025&lang='+lang+'#race=9693');await p.locator('[data-analysis-open]').click();const input=p.locator('#f1-question');await input.waitFor();assert(await input.evaluate(e=>document.activeElement===e));const styles=await input.evaluate(e=>{const s=getComputedStyle(e);return {height:e.getBoundingClientRect().height,fontSize:s.fontSize,border:s.borderTopWidth,color:s.color}});assert(styles.height>=144);assert.equal(styles.fontSize,'18px');assert.equal(styles.border,'2px');assert.equal(await p.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);await input.fill(lang==='ko'?'2024년과 2025년 노리스 포인트 비교해줘':'Compare 2024 and 2025 Norris points');await p.locator('.nl-form button[type=submit]').click();const output=await p.locator('.nl-output').innerText();assert(output.includes('15')&&output.includes('25'),JSON.stringify({lang,width,output,status:await p.locator('.nl-status').innerText()}));checks.push({lang,width,styles,comparison:[15,25]});if(width!==768){await input.scrollIntoViewIfNeeded();await p.screenshot({path:__dirname+`/analysis-${lang}-${width}.png`});}}
}
for(const lang of ['ko','en']){await p.setViewportSize({width:390,height:900});await p.goto(base+'/f1/index.html?year=2025&lang='+lang+'#race=9693');await p.locator('[data-analysis-open]').click();const q=p.locator('#f1-question');await q.fill(lang==='ko'?'막스 베르스타펜 포인트 보여줘':'Max Verstappen points');await p.locator('.nl-form button[type=submit]').click();const text=await p.locator('.nl-output').innerText();assert(text.includes(lang==='ko'?'막스 베르스타펜':'Max VERSTAPPEN'),text);assert(!text.includes('페르스타펜'));assert.equal(await p.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);checks.push({lang,driverQuery:text});await p.screenshot({path:__dirname+'/names-'+lang+'.png'});}
assert.deepEqual(errors,[]);fs.writeFileSync(__dirname+'/browser-result.json',JSON.stringify({status:'PASS',checks,pageErrors:errors},null,2));console.log('PASS: bilingual GP title, focus shortcut, visible 144px input, year comparison, no overflow at 390/768/1440');
}finally{await browser.close();server.closeAllConnections();await new Promise(r=>server.close(r))}})().catch(e=>{console.error(e);process.exitCode=1});


