// English behavior checks, using the same DOM stub as the Korean regression suite.
const fs=require('fs'),vm=require('vm'),assert=require('assert');
const harness=fs.readFileSync(__dirname+'/check.cjs','utf8').split('let checks=0;')[0]
 .replace('async function main(){','').replace("__dirname+'/index.html'","__dirname+'/index.en.html'");
const sandbox={require,__dirname,console};vm.createContext(sandbox);
vm.runInContext(harness+'\nglobalThis.testContext=context;globalThis.testNodes=nodes;globalThis.testEvents=events;globalThis.testData=data;',sandbox);
const context=sandbox.testContext,nodes=sandbox.testNodes,events=sandbox.testEvents,data=sandbox.testData;
const get=id=>nodes.get(id),run=code=>vm.runInContext(code,context);
let checks=0;function test(name,fn){fn();checks++;console.log('PASS '+name)}
const html=fs.readFileSync(__dirname+'/index.en.html','utf8');
test('English document and active language navigation',()=>{assert(html.includes('<html lang="en">'));assert(html.includes('id="language-en" aria-current="page"'));assert(html.includes('hreflang="ko"'));assert(html.includes('Your Football Clubhouse'))});
test('all selected leagues and historical clubs retained',()=>{assert.strictEqual(Object.values(data.teams).filter(t=>t.league==='EPL').length,27);assert.strictEqual(Object.values(data.teams).filter(t=>t.league==='La_liga').length,29)});
test('English UI contains no untranslated Korean except language link',()=>{const stripped=html.replace(/<script id="data" type="application\/json">[\s\S]*?<\/script>/,'').replace('한국어','');assert(!/[가-힣]/.test(stripped));assert(html.includes('Premier League'));assert(html.includes('LaLiga'))});
test('all metric names, definitions and units are English',()=>{assert.strictEqual(Object.keys(data.metric_meta).length,47);Object.values(data.metric_meta).forEach(m=>{assert(!/[가-힣]/.test(m.label+m.description+m.unit));assert(m.description.length>10)});assert.strictEqual(data.metric_meta['PASS/M'].unit,'Per match')});
test('English profile for Premier League',()=>{run('openTeam("understat:83")');assert.strictEqual(get('league').value,'EPL');assert.strictEqual(get('heading').textContent,'Club profile');assert(get('teamcontent').innerHTML.includes('Premier League'));assert(get('teamcontent').innerHTML.includes('Attack & defence in selected matches'))});
test('English profile for LaLiga',()=>{run('openTeam("understat:148")');assert.strictEqual(get('league').value,'La_liga');assert(get('teamcontent').innerHTML.includes('LaLiga'));assert(get('teamcontent').innerHTML.includes('Barcelona'))});
test('switching language preserves selected team hash',()=>{context.window.location.hash='#team=understat%3A83';events.hashchange();assert.strictEqual(get('teamselect').value,'understat:83');assert.strictEqual(get('language-ko').attributes.href,'index.html#team=understat%3A83');assert.strictEqual(get('language-en').attributes.href,'index.en.html#team=understat%3A83')});
test('English season history retains raw results',()=>{get('season').value='2023/24';get('season').onchange();assert.strictEqual(run('selectedGames("understat:83").length'),38);assert(get('teamcontent').innerHTML.includes('Season history'));assert(get('teamcontent').innerHTML.includes('Points per match'))});
test('English venue and recent filters work',()=>{get('venue').value='home';get('venue').onchange();assert.strictEqual(run('selectedGames("understat:83").length'),19);get('rangefilter').value='5';get('rangefilter').onchange();assert.strictEqual(run('selectedGames("understat:83").length'),5);assert(run('scopeText()').includes('Last 5 matches'))});
test('English metric names and legacy codes are searchable',()=>{get('metricgroup').value='all';for(const query of ['Penalties conceded','PKC','not the number of goals conceded']){get('metricsearch').value=query;run('renderSnapshot()');assert(get('snapshotstats').innerHTML.includes('Penalties conceded'));assert(get('snapcount').textContent.includes('1 / 47'))}});
test('English metric explanation opens with semantic distinctions',()=>{run('openMetricHelp("PKC",$("metricsearch"))');assert.strictEqual(get('metrichelptitle').textContent,'Penalties conceded');assert(get('metrichelpmeaning').textContent.includes('not the number of goals conceded'));assert(get('metrichelpreading').textContent.includes('not goals conceded'));run('openMetricHelp("TKL-LM",$("teamsearch"))');assert.strictEqual(get('metrichelptitle').textContent,'Last-man tackles')});
test('English per-match explanation selects correct unit branch',()=>{run('openMetricHelp("PASS/M",$("metricsearch"))');assert(get('metrichelpreading').textContent.includes('per-match average'))});
test('English invalid dates and empty-state text',()=>{get('rangefilter').value='custom';get('rangefilter').onchange();get('startdate').value='2023-09-01';get('enddate').value='2023-08-01';get('enddate').onchange();assert.strictEqual(get('filtererror').textContent,'Start date must be on or before end date.');assert(get('teamcontent').innerHTML.includes('No matches meet these filters.'))});
test('English site preserves data except translated presentation metadata',()=>{const ko=JSON.parse(fs.readFileSync(__dirname+'/index.html','utf8').match(/<script id="data" type="application\/json">([\s\S]*?)<\/script>/)[1]);const en=JSON.parse(JSON.stringify(data));delete ko.metric_meta;delete en.metric_meta;assert.deepStrictEqual(en,ko)});
test('canonical English entry matches archived English version',()=>{assert.strictEqual(fs.readFileSync(__dirname+'/../index.en.html','utf8'),html)});
fs.writeFileSync(__dirname+'/logic-check.en.json',JSON.stringify({method:'Node VM with DOM stub; not actual browser rendering',checks,failures:0},null,2)+'\n');
console.log(checks+' English checks passed.');
