const fs=require('node:fs'),assert=require('node:assert/strict');
const Engine=require('../record-engine.cjs');require('../../f1/release-0.7.1/replay/metrics.js');require('../../f1/release-0.9.2/driver-names.js');require('./f1-natural-analysis.js');require('../../f1/release-0.9.2/history-analysis.js');const Workbench=require('./workbench.js');
function json(file,id){return JSON.parse(fs.readFileSync(file,'utf8').match(new RegExp('<script id="'+id+'" type="application/json">([\\s\\S]*?)</script>'))[1]);}
const data=json(__dirname+'/../../index.html','data'),e=Engine.create(data),defaults={team:'understat:83',league:'EPL',season:'2026/27'};let checks=[];
let a=e.parse('아스널 최근 5경기 경기당 기대 득점 보여줘',defaults);assert(!a.error);assert.equal(a.last,5);assert(a.perMatch);
let b=e.parse('첼시도 추가해줘',defaults,a);assert(!b.error);assert.equal(b.last,5);assert.equal(b.metric,'xg');assert.equal(b.teams.length,2);assert(b.teams.includes('understat:83'));assert.equal(b.tool,'comparison');
let c=e.parse('작년으로 바꿔줘',defaults,b);assert.equal(c.season,'2025/26');assert.deepEqual(c.teams,b.teams);assert.equal(c.last,5);let d=e.parse('최근 10경기로 변경해줘',defaults,c);assert.equal(d.last,10);assert.equal(d.season,'2025/26');assert.deepEqual(d.teams,c.teams);assert(e.parse('슈팅 보여줘',defaults,d).error);const trend=e.parse('아스널 최근 5경기 득점과 기대 득점 비교해줘',defaults);const addTrend=e.parse('첼시도 추가해줘',defaults,trend);assert.equal(addTrend.tool,'comparison');assert.equal(addTrend.teams.length,2);assert.equal(e.execute(addTrend).rows.length,2);checks.push('football add/year/period retains conditions; added team not silently dropped; unsupported metric rejected');
const main=json(__dirname+'/../../f1/index.html','dataset'),past=json(__dirname+'/../../f1/index.html','f1-query-history'),hist={races:[...json(__dirname+'/../../f1/index.html','f1-history-2024').races,...past.races,...main.races]},race=main.races.find(x=>x.state==='completed'&&x.session.session_key===11234),core=globalThis.MatchLabF1Natural,legacy=globalThis.MatchLabF1History;assert(race);const planner=Workbench.f1Planner({race,history:hist,core,legacy});
a=planner.prepare('노리스 최근 5경기 평균 랩타임 보여줘');assert(!a.error,JSON.stringify(a));assert.equal(a.period.mode,'recent');assert.equal(a.metrics[0],'mean_lap');assert.equal(a.driverNames.length,1);
b=planner.prepare('피아스트리도 추가해줘',a);assert(!b.error,JSON.stringify(b));assert.equal(b.driverNames.length,2);assert.equal(b.period.count,5);assert.deepEqual(b.metrics,a.metrics);
c=planner.prepare('작년으로 바꿔줘',b);assert(!c.error,JSON.stringify(c));assert.equal(c.period.year,2025);assert.equal(c.period.mode,'recent');assert.deepEqual(c.driverNames,b.driverNames);let result=planner.execute(c);assert.equal(result.kind,'recent');assert.equal(result.races.length,5);assert(result.races.every(r=>Date.parse(r.session.date_start)<=Date.parse(race.session.date_start)));
for(const row of result.result.rows){const means=result.races.map(r=>{const driver=r.records.drivers.find(d=>d.full_name.toLowerCase()===row.name.toLowerCase());if(!driver)return null;return globalThis.MatchLabF1Metrics.calculate(r,driver.driver_number).find(x=>x.key==='mean_lap')?.value;}).filter(v=>typeof v==='number');if(means.length){const expected=means.reduce((a,b)=>a+b,0)/means.length;assert(Math.abs(row.value-expected)<1e-8);}else assert.equal(row.value,null);assert.equal(row.recorded,means.length);}
const present=planner.execute(b);assert.equal(present.kind,'recent');assert(present.result.rows.some(r=>r.recorded>0));for(const row of present.result.rows){const values=present.races.map(r=>{const dn=r.records.drivers.find(d=>d.full_name===row.name)?.driver_number;const laps=(r.records.laps||[]).filter(l=>l.driver_number===dn&&Number.isFinite(l.lap_duration)&&l.lap_duration>0);return laps.length?laps.reduce((s,l)=>s+l.lap_duration,0)/laps.length:null;}).filter(v=>v!==null);if(values.length)assert(Math.abs(row.value-values.reduce((a,b)=>a+b,0)/values.length)<1e-8);else assert.equal(row.value,null);}checks.push('F1 add/year retains conditions; current means independently calculated; missing archived laps remain null');
const zero=planner.prepare('노리스 최근 0경기 포인트 보여줘');assert.equal(zero.error,'range');assert(planner.prepare('피아스트리 추가해줘').error);assert(planner.prepare('2027년 노리스 포인트').error);assert(planner.prepare('노리스 drop table 포인트').error);checks.push('invalid period, no prior context, future year and arbitrary code rejected');
let mixed=planner.prepare('막스 베르스타펜 최근 5경기 포인트');mixed=planner.prepare('작년으로 바꿔줘',mixed);result=planner.execute(mixed);assert(result.result.rows[0].name.toLowerCase().includes('verstappen'));assert(result.races.every(r=>r.session.year===2025));checks.push('historical identity matched by name despite jersey-number change');
let histPlan=planner.prepare('2024년과 2025년 노리스 포인트 비교해줘');assert.equal(histPlan.kind,'legacy');result=planner.execute(histPlan);assert.equal(result.result.results.length,2);checks.push('existing multi-year same-GP query preserved');
for(const file of ['index.html','index.en.html','f1/index.html']){const now=fs.readFileSync(__dirname+'/../../'+file,'utf8'),before=fs.readFileSync(__dirname+'/'+file.replaceAll('/','-')+'.before','utf8');for(const m of before.matchAll(/<script[^>]*type="application\/json"[^>]*>[\s\S]*?<\/script>/g))assert(now.includes(m[0]),file+' payload changed');}checks.push('all football/F1 embedded recorded and predicted JSON unchanged');
fs.writeFileSync(__dirname+'/planner-result.json',JSON.stringify({status:'PASS',checks},null,2));console.log('PASS '+checks.length+' planner groups');
