/* Editable recorded-data plans. No arbitrary code execution, model training or invented data. */
(function(g){'use strict';
const clone=x=>JSON.parse(JSON.stringify(x)),esc=x=>String(x??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const norm=s=>String(s||'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/[^a-z0-9]/g,'');
const select=(key,label,options,value,multiple=false)=>`<label>${esc(label)}<select data-plan-field="${key}" ${multiple?'multiple size="4"':''}>${options.map(([v,t])=>`<option value="${esc(v)}" ${(multiple?value.includes(v):String(value)===String(v))?'selected':''}>${esc(t)}</option>`).join('')}</select></label>`;
function review({host,form,input,status,out,prepare,fields,read,execute,render,onCommit,en=false}){
 const panel=document.createElement('section');panel.className='ml-plan-review';panel.hidden=true;form.after(panel);let previous=null,draft=null,version=0;
 const tr=(a,b)=>en?b:a;
 function clear(){version++;previous=null;draft=null;panel.hidden=true;panel.replaceChildren();input.value='';out.replaceChildren();status.textContent=tr('이전 조건을 초기화했습니다.','Previous conditions cleared.');input.focus();onCommit?.(null);}
 function message(error){return tr(({ambiguous:'잘했다는 기준을 골라 주세요.',context:'먼저 분석을 한 번 실행한 뒤 조건을 이어서 바꿔 주세요.',range:'기간·경기 수 범위를 확인해 주세요.',too_many:'비교 대상과 지표는 각각 최대 4개입니다.',future:'종료되지 않은 경기에는 기록이 없습니다. 현재 GP의 예측 지표를 선택해 주세요.',no_data:'선택한 기간에 확보한 기록이 없습니다.',unsupported:'이 질문은 지원 범위를 벗어납니다. 대상·기간·조회 가능한 지표를 구체적으로 적어 주세요.'})[error]||'조건을 해석하지 못했습니다. 대상·기간·지표를 확인해 주세요.', 'Check the question, available records and supported metrics.');}
 function clarify(question){panel.hidden=false;panel.innerHTML=`<h4>${tr('어떤 기준으로 볼까요?','Choose a criterion')}</h4><p>${tr('기준을 정한 뒤 분석 조건을 확인합니다.','Choose a metric before reviewing the plan.')}</p><div class="ml-plan-actions">${(prepare.sport==='football'?[['승점','Points'],['승률','Win rate'],['기대 득점','Expected goals']]:[['포인트','Points'],['최종 순위','Final position'],['평균 랩타임','Mean lap time']]).map(([ko,english])=>`<button type="button" data-clarify="${esc(en?english:ko)}">${esc(en?english:ko)}</button>`).join('')}</div>`;panel.querySelectorAll('[data-clarify]').forEach(b=>b.onclick=()=>{input.value=question.replace(/잘한|잘하는|좋은|좋았던|best|better|good/gi,'')+' '+b.dataset.clarify+' '+(en?'ranking':'순위');request(input.value);});status.textContent=message('ambiguous');}
 function stage(plan){draft=null;out.replaceChildren();if(plan.error){panel.hidden=true;status.textContent=message(plan.error);return;}draft=clone(plan);panel.hidden=false;panel.innerHTML=`<h4>${tr('분석 조건 확인','Review analysis conditions')}</h4><p>${tr('필요한 항목을 수정한 뒤 결과를 확인하세요.','Edit the conditions, then run the analysis.')}</p>${plan.follow?`<p class="ml-plan-inherited">${tr('이전 분석의 지정하지 않은 조건을 이어받았습니다.','Unspecified conditions were retained from the previous analysis.')}</p>`:''}<div class="ml-plan-fields">${fields(draft,en)}</div><div class="ml-plan-actions"><button type="button" data-plan-apply>${tr('이 조건으로 분석','Run with these conditions')}</button><button type="button" data-plan-reset>${tr('새 질문 시작','Start a new question')}</button></div>`;panel.querySelector('[data-plan-reset]').onclick=clear;panel.querySelector('[data-plan-apply]').onclick=()=>{try{const edited=read(clone(draft),panel);if(edited.error){status.textContent=message(edited.error);return;}const result=execute(edited);if(result.error){status.textContent=message(result.error);out.replaceChildren();return;}render(result,edited);previous=clone(edited);draft=clone(edited);onCommit?.(edited);status.textContent=tr('확인한 조건으로 분석했습니다. 이어서 조건을 바꿔 질문할 수 있습니다.','Analysis complete. You can ask a follow-up to change conditions.');}catch{status.textContent=message('unsupported');out.replaceChildren();}};status.textContent=tr('해석한 조건을 확인해 주세요. 아직 분석을 실행하지 않았습니다.','Review the interpreted conditions. Analysis has not run yet.');}
 async function request(question,remote){const ticket=++version;draft=null;panel.hidden=true;out.replaceChildren();if(typeof question!=='string'||!question.trim()||question.length>500){status.textContent=message('unsupported');return {error:'unsupported'};}if(/잘한|잘하는|좋은|좋았던|\b(?:better|good)\b/i.test(question)){clarify(question);return {clarification:true};}if(remote){status.textContent=tr('분석 조건을 해석하고 있습니다.','Interpreting analysis conditions.');try{const p=await remote(previous);if(ticket!==version)return;stage(p);return p;}catch{if(ticket===version)status.textContent=tr('AI 연결에 실패했습니다. 저장 기록 분석을 선택해 다시 시도해 주세요.','AI connection failed. Try stored-record analysis.');return {error:'provider'};}}const p=prepare(question,previous);stage(p);return p;}
 return {request,stage,clear,cancelDraft(){version++;draft=null;panel.hidden=true;out.replaceChildren();},get previous(){return previous;},destroy(){version++;panel.remove();}};
}
function football({host,form,input,status,out,engine,data,defaults,render,onCommit,en=false}){
 const tr=(a,b)=>en?b:a,teams=Object.entries(data.teams);const prepare=(q,prev)=>engine.parse(q,defaults(),prev);prepare.sport='football';
 function fields(p){if(!['team','comparison','ranking','venue','trend'].includes(p.tool))return `<p>${tr('기록 조회 지표로 다시 질문해 주세요.','Ask for a recorded-data metric.')}</p>`;return select('teams',tr('구단 — 여러 구단 선택 가능','Clubs — multiple selection'),teams.map(([id,t])=>[id,t.name]),p.tool==='ranking'?[]:p.teams,true)+select('league',tr('리그','League'),[['EPL','Premier League'],['La_liga','LaLiga']],p.league)+select('season',tr('시즌','Season'),['2023/24','2024/25','2025/26','2026/27'].map(x=>[x,x]),p.season)+select('last',tr('경기 범위','Matches'),[[0,tr('시즌 전체','Full season')],...[3,5,10,15,20,38,...(p.last?[p.last]:[])].filter((x,i,a)=>a.indexOf(x)===i).sort((a,b)=>a-b).map(x=>[x,tr('최근 '+x+'경기','Last '+x+' matches')])],p.last||0)+select('metric',tr('지표','Metric'),Object.entries(g.MatchDeskAnalysis.metrics).map(([k,m])=>[k,m[en?'en':'ko']]),p.metric)+select('venue',tr('장소','Venue'),[['all',tr('홈·원정 전체','All venues')],['home',tr('홈','Home')],['away',tr('원정','Away')]],p.venue)+select('perMatch',tr('계산 방식','Calculation'),[['false',tr('합계','Total')],['true',tr('경기당 평균','Per-match average')]],String(p.perMatch))+select('order',tr('정렬','Order'),[['desc',tr('큰 값부터','Highest first')],['asc',tr('작은 값부터','Lowest first')]],p.order||'desc')+(p.compareGoals?`<p>${tr('기대 득점과 실제 득점 비교를 유지합니다.','Expected-vs-actual goals comparison is retained.')}</p>`:'');}
 function read(p,panel){if(!['team','comparison','ranking','venue','trend'].includes(p.tool))return {error:'unsupported'};const val=k=>panel.querySelector('[data-plan-field='+k+']').value;p.teams=Array.from(panel.querySelector('[data-plan-field=teams]').selectedOptions,o=>o.value);p.league=val('league');p.season=val('season');p.last=Number(val('last'))||null;p.metric=val('metric');p.venue=val('venue');p.perMatch=val('perMatch')==='true';p.order=val('order');if(p.teams.length>4)return {error:'too_many'};if(p.teams.some(id=>data.teams[id]?.league!==p.league))return {error:'unsupported'};if(!p.teams.length&&p.tool!=='ranking')return {error:'unsupported'};if(p.tool==='ranking'&&p.teams.length)p.tool=p.teams.length>1?'comparison':'team';if(p.teams.length>1&&['team','comparison','venue','trend'].includes(p.tool)){p.tool='comparison';p.compareGoals=false;}if(p.metric!=='xg')p.compareGoals=false;if(p.tool==='trend'&&!p.compareGoals)p.tool='team';return p;}
 return review({host,form,input,status,out,prepare,fields,read,execute:p=>{const r=engine.execute(p);return r.status==='ok'?r:{error:r.status==='empty'?'no_data':'unsupported'};},render,onCommit,en});
}
function f1Planner({race,prediction,history,core,legacy}){
 const currentYear=Number(race.session.year||race.session.date_start.slice(0,4)),cutoff=Date.parse(race.session.date_start),catalogue=[...new Map([...(history?.races||[]),race].map(r=>[r.session.session_key,r])).values()];
 const roster=[...new Map(catalogue.flatMap(r=>(r.records?.drivers||[])).concat(prediction?.drivers||[]).map(d=>[norm(d.full_name||d.name),{...d,full_name:d.full_name||d.name}])).values()];
 const synthetic={...race,state:'completed',records:{drivers:roster.map((d,i)=>({...d,driver_number:i+1000}))}};
 const nameOf=n=>synthetic.records.drivers.find(d=>d.driver_number===n)?.full_name;
 function periodRaces(p){if(p.period.mode==='gp'){if(p.period.year===currentYear)return [race];const scope=g.MatchLabF1History.select(p.period.year+' records',race,history);return scope.selected.map(s=>s.race);}const all=catalogue.filter(r=>r.state==='completed'&&r.session.session_name==='Race'&&Number(r.session.year||r.session.date_start.slice(0,4))===p.period.year&&Date.parse(r.session.date_start)<=cutoff).sort((a,b)=>Date.parse(a.session.date_start)-Date.parse(b.session.date_start)||a.session.session_key-b.session.session_key);return all.slice(-p.period.count);}
 function prepare(q,previous){
  if(!q.trim()||q.length>500)return {error:'unsupported'};
  const manyYears=[...q.matchAll(/\b20\d{2}\b/g)].length>1,overview=/기록|성적|records|results/i.test(q)&&/작년|재작년|20\d{2}|last year/i.test(q);
  if((manyYears||overview)&&legacy){const p=legacy.parse(q,race,prediction,previous?.legacyPlan,history);return p.error?p:{legacyPlan:p,kind:'legacy'};}
  let text=q,year=null,count=null;const recent=text.match(/(?:최근|last|recent)\s*(\d+)\s*(?:경기|그랑프리|gp|races?)/i);if(recent){count=Number(recent[1]);text=text.replace(recent[0],' ');if(count<1||count>24)return {error:'range'};}
  const explicit=text.match(/\b(20\d{2})\s*년?/);if(explicit){year=Number(explicit[1]);text=text.replace(explicit[0],' ');}else if(/재작년|year before last/i.test(text)){year=currentYear-2;text=text.replace(/재작년|year before last/gi,' ');}else if(/작년|지난\s*시즌|last year|previous year/i.test(text)){year=currentYear-1;text=text.replace(/작년|지난\s*시즌|last year|previous year/gi,' ');}else if(/올해|이번\s*시즌|this year/i.test(text)){year=currentYear;text=text.replace(/올해|이번\s*시즌|this year/gi,' ');}
  if(year!==null&&(year<2024||year>currentYear))return {error:'range'};
  const followWords=/추가|더해|바꿔|변경|대신|반대로|역순|제거|빼\s*줘|add|replace|change|instead|reverse|remove/i,follow=!!previous&&previous.kind!=='legacy'&&(followWords.test(text)||count!==null||year!==null);
  if(followWords.test(text)&&!previous)return {error:'context'};
  const add=/추가|더해|\badd\b/i.test(text),remove=/제거|빼\s*줘|\bremove\b/i.test(text),reverse=/반대로|역순|reverse/i.test(text);
  text=text.replace(/추가(?:해\s*줘(?:요)?)?|더해(?:\s*줘)?|바꿔(?:\s*줘(?:요)?)?|변경(?:해\s*줘)?|대신|제거(?:해\s*줘)?|빼\s*줘|해\s*줘(?:요)?|(?:으로|로)(?=\s|$)|\b(?:add|replace|change|instead|remove|to|in|with)\b/gi,' ');
  const prior=follow?clone(previous):null;if(prior){text=text.replace(/반대로|역순|reverse|opposite/gi,' ');}
  let parsed=core.parse(text,synthetic,prediction);if(prior&&(parsed.error==='unsupported'||(parsed.error==='question'&&!text.trim()))){parsed=core.parse(text+' '+prior.metrics.map(k=>k==='laps'?'랩타임 변화':g.MatchLabF1Metrics.registry[k]?.ko).join(' '),synthetic,prediction);}
  if(parsed.error)return parsed;
  let driverNames=parsed.drivers.map(nameOf);if(prior){if(add)driverNames=[...new Set([...prior.driverNames,...driverNames])];else if(remove)driverNames=prior.driverNames.filter(n=>!driverNames.some(x=>norm(x)===norm(n)));else if(!driverNames.length)driverNames=prior.driverNames;}
  if(driverNames.length>4||parsed.metrics.length>4)return {error:'too_many'};
  const p={kind:'f1',driverNames,metrics:parsed.metrics,metric:parsed.metric,conditions:prior?{...prior.conditions,...parsed.conditions}:parsed.conditions,period:prior?prior.period:{mode:'gp',year:currentYear,count:5},aggregation:prior?.aggregation||'auto',follow,session_key:race.session.session_key};
  if(count!==null)p.period={...p.period,mode:'recent',count};if(year!==null)p.period.year=year;
  if(reverse){const low=['mean_lap','best_lap','final_position','expected_rank','mean_stop','mean_pit_lane'].includes(p.metric);p.conditions.order=(p.conditions.order||(low?'asc':'desc'))==='asc'?'desc':'asc';}
  if(prior&&JSON.stringify(parsed.metrics)!==JSON.stringify(prior.metrics))p.aggregation='auto';if(/평균|경기당|average|mean/i.test(q))p.aggregation='mean';
  return validate(p);
 }
 function validate(p){if(p.kind==='legacy')return p;if(p.session_key!==race.session.session_key||!['gp','recent'].includes(p.period.mode)||!Number.isInteger(p.period.year)||p.period.year<2024||p.period.year>currentYear||!Number.isInteger(p.period.count)||p.period.count<1||p.period.count>24)return {error:'range'};if(p.driverNames.length>4||p.metrics.length>4)return {error:'too_many'};if(p.metrics.some(k=>!core.queryKeys.includes(k)&&k!=='laps'))return {error:'unsupported'};const numeric=['laps','final_status'];if((p.conditions.threshold||p.conditions.limit||p.conditions.order)&&(p.metrics.length!==1||numeric.includes(p.metric)))return {error:'unsupported'};if((p.conditions.from||p.conditions.excludePit)&&p.metrics.some(k=>!['laps','best_lap','mean_lap','valid_laps','lap_std','sector_1','sector_2','sector_3','top_speed'].includes(k)))return {error:'unsupported'};if(p.conditions.threshold?.unit){const u=p.conditions.threshold.unit;if(/초|seconds?|^s$/.test(u)&&!['best_lap','mean_lap','lap_std','sector_1','sector_2','sector_3','mean_stop','mean_pit_lane'].includes(p.metric))return {error:'unsupported'};if(/km|킬로/.test(u)&&p.metric!=='top_speed')return {error:'unsupported'};if(u==='%'&&p.metric!=='win_probability')return {error:'unsupported'};if(/포인트|점|points?/.test(u)&&!['points','recent5_points'].includes(p.metric))return {error:'unsupported'};}if(p.period.mode==='recent'&&p.metrics.some(k=>k==='laps'||k==='final_status'||g.MatchLabF1Metrics.registry[k]?.category==='prediction'))return {error:'unsupported'};return p;}
 function execute(p){if(p.kind==='legacy')return {kind:'legacy',result:legacy.execute(p.legacyPlan,race,prediction,history)};const selected=periodRaces(p);if(!selected.length)return {error:'no_data'};const results=[];
  for(const r of selected){const ds=r.state==='completed'?(r.records?.drivers||[]):(prediction?.drivers||[]),numbers=ds.filter(d=>p.driverNames.some(n=>norm(n)===norm(d.full_name||d.name))).map(d=>d.driver_number);if(p.driverNames.length&&!numbers.length)continue;const plan={metric:p.metric,metrics:p.metrics,drivers:numbers,conditions:p.period.mode==='recent'?{from:p.conditions.from,to:p.conditions.to,excludePit:p.conditions.excludePit}:p.conditions,session_key:r.session.session_key};if(r.state!=='completed'&&p.metrics.some(k=>g.MatchLabF1Metrics.registry[k]?.category!=='prediction'))return {error:'future'};results.push({race:r,result:core.execute(plan,r,r===race?prediction:history?.predictions?.[String(r.session.session_key)])});}
  if(!results.length)return {error:'no_data'};if(p.period.mode==='gp')return {kind:'single',result:results[0].result,races:selected,plan:p};
  const names=p.driverNames.length?p.driverNames:[...new Map(results.flatMap(x=>x.result.rows||x.result.results?.flatMap(y=>y.rows)||[]).map(r=>[norm(r.name),r.name])).values()];
  const summaries=p.metrics.map(metric=>{let rows=names.map(name=>{const samples=results.map(x=>({race:x.race,row:(x.result.kind==='multiple'?x.result.results.find(z=>z.metric===metric):x.result)?.rows?.find(z=>norm(z.name)===norm(name))})).filter(x=>typeof x.row?.value==='number'&&Number.isFinite(x.row.value));const values=samples.map(x=>x.row.value);const method=p.aggregation==='mean'?'mean':['points','completed_laps','valid_laps','pit_entries','stint_count'].includes(metric)?'sum':metric==='best_lap'?'min':metric==='top_speed'?'max':'mean';const value=!values.length?null:method==='sum'?values.reduce((a,b)=>a+b,0):method==='min'?Math.min(...values):method==='max'?Math.max(...values):values.reduce((a,b)=>a+b,0)/values.length;return {name,value,recorded:values.length,method,dates:samples.map(x=>x.race.session.date_start.slice(0,10))};});
   if(p.conditions.threshold){const t=p.conditions.threshold;rows=rows.filter(r=>r.value!==null&&({lt:r.value<t.value,lte:r.value<=t.value,gt:r.value>t.value,gte:r.value>=t.value})[t.op]);}const low=['mean_lap','best_lap','final_position','mean_stop','mean_pit_lane','lap_std','sector_1','sector_2','sector_3'].includes(metric);rows.sort((a,b)=>a.value===null?1:b.value===null?-1:(a.value-b.value)*((p.conditions.order|| (low?'asc':'desc'))==='asc'?1:-1));if(p.conditions.limit)rows=rows.slice(0,p.conditions.limit);const unit=results.map(x=>x.result.kind==='multiple'?x.result.results.find(z=>z.metric===metric):x.result).find(Boolean)?.unit||'';return {kind:'bar',metric,unit,rows};});return {kind:'recent',result:summaries.length===1?summaries[0]:{kind:'multiple',results:summaries},races:selected,plan:p};
 }
 return {prepare,execute,validate,roster,currentYear};
}
function f1({host,race,prediction,history,core,legacy,locale='ko'}){const en=locale==='en',tr=(a,b)=>en?b:a,planner=f1Planner({race,prediction,history,core,legacy});planner.prepare.sport='f1';
 function fields(p){if(p.kind==='legacy')return `<p>${tr('조회 연도','Years')}: ${esc(p.legacyPlan.years?.join(', '))} · ${tr('같은 GP의 과거 기록','Historical records for the same GP')}</p>`;const driverOptions=planner.roster.map(d=>[d.full_name,g.MatchLabF1Names.display(d.full_name,en)]);const available=[...core.queryKeys,'laps'];return select('drivers',tr('드라이버 — 선택하지 않으면 전체','Drivers — none selects all'),driverOptions,p.driverNames,true)+select('metrics',tr('지표 — 최대 4개','Metrics — up to four'),[...new Set([...available,...p.metrics])].map(k=>[k,k==='laps'?tr('랩타임 변화','Lap-time trend'):g.MatchLabF1Metrics.registry[k][en?'en':'ko']]),p.metrics,true)+select('period',tr('경기 범위','Race scope'),[['gp',tr('선택한 GP','Selected GP')],['recent',tr('최근 종료 GP','Recent completed GPs')]],p.period.mode)+select('year',tr('연도','Year'),[2024,2025,2026].filter(y=>y<=planner.currentYear).map(y=>[y,y]),p.period.year)+select('count',tr('최근 GP 수','Recent GP count'),[3,5,10,15,24,p.period.count].filter((v,i,a)=>a.indexOf(v)===i).sort((a,b)=>a-b).map(n=>[n,n]),p.period.count)+select('aggregation',tr('여러 GP 계산 방식','Across-GP calculation'),[['auto',tr('지표별 기본','Metric default')],['mean',tr('GP별 값의 평균','Mean of GP values')]],p.aggregation)+select('order',tr('정렬','Order'),[['auto',tr('지표에 맞게','Metric default')],['asc',tr('작은 값부터','Lowest first')],['desc',tr('큰 값부터','Highest first')]],p.conditions.order||'auto')+(Object.keys(p.conditions).filter(k=>k!=='order').some(k=>p.conditions[k]!=null)?`<p class="ml-plan-scope">${tr('추가 조건','Additional conditions')}: ${esc([p.conditions.from?tr('랩 '+p.conditions.from+'–'+p.conditions.to,'Laps '+p.conditions.from+'–'+p.conditions.to):'',p.conditions.excludePit?tr('피트랩 제외','Exclude pit laps'):'',p.conditions.threshold?tr('값 조건','Value threshold')+' '+({lt:'<',lte:'≤',gt:'>',gte:'≥'}[p.conditions.threshold.op]||p.conditions.threshold.op)+' '+p.conditions.threshold.value+' '+p.conditions.threshold.unit:'',p.conditions.limit?tr('상위 '+p.conditions.limit+'명','Top '+p.conditions.limit):''].filter(Boolean).join(' · '))}<label><input type="checkbox" data-clear-restrictions> ${tr('추가 조건 지우기','Clear additional conditions')}</label></p>`:'')+`<p class="ml-plan-scope">${tr('최근 GP는 선택한 경기 시점까지의 해당 연도 종료 기록만 사용합니다. 기본 계산에서 포인트·횟수는 합계, 평균 랩타임은 GP별 평균의 평균입니다.','Recent GPs use completed records in the chosen year up to this race. By default, points/counts are summed; mean lap time averages GP-level means.')}</p>`;}
 function read(p,panel){if(p.kind==='legacy')return p;const val=k=>panel.querySelector('[data-plan-field='+k+']').value;p.driverNames=Array.from(panel.querySelector('[data-plan-field=drivers]').selectedOptions,o=>o.value);p.metrics=Array.from(panel.querySelector('[data-plan-field=metrics]').selectedOptions,o=>o.value);if(!p.metrics.length)return {error:'unsupported'};p.metric=p.metrics[0];p.period={mode:val('period'),year:Number(val('year')),count:Number(val('count'))};p.aggregation=val('aggregation');if(panel.querySelector('[data-clear-restrictions]')?.checked)p.conditions={};const order=val('order');if(order==='auto')delete p.conditions.order;else p.conditions.order=order;return planner.validate(p);}
 return review({host,form:host.querySelector('form'),input:host.querySelector('textarea'),status:host.querySelector('.nl-status'),out:host.querySelector('.nl-output'),prepare:planner.prepare,fields,read,execute:planner.execute,render:(r,p)=>{const out=host.querySelector('.nl-output');if(r.kind==='legacy'){out.innerHTML=legacy.draw(r.result,en);return;}out.innerHTML=(r.kind==='recent'?`<p>${tr('확보한 종료 GP','Collected completed GPs')}: ${r.races.length}/${p.period.count} · ${esc(r.races[0].session.date_start.slice(0,10))}–${esc(r.races.at(-1).session.date_start.slice(0,10))}</p>`:'')+core.draw(r.result,en)+(r.kind==='recent'?`<p>${tr('지표가 미확보인 GP는 해당 지표 계산에서 제외합니다.','GPs with missing values are excluded from that metric.')}</p><div class="ml-plan-coverage">${(r.result.kind==='multiple'?r.result.results:[r.result]).flatMap(x=>x.rows.map(row=>`<p>${esc(g.MatchLabF1Names.display(row.name,en))}: ${row.recorded} ${tr('경기 기록','recorded GPs')} · ${esc(en?row.method:({sum:'합계',mean:'GP별 값의 평균',min:'최솟값',max:'최댓값'}[row.method]||row.method))}</p>`)).join('')}</div>`:'');},en});
}
const api={football,f1,f1Planner};g.MatchLabAnalysisWorkbench=api;if(typeof module!=='undefined'&&module.exports)module.exports=api;
if(typeof document!=='undefined'){const s=document.createElement('style');s.id='ml-plan-styles';s.textContent=`.ml-plan-review{border:2px solid #2d7386;border-radius:14px;background:#f4fafc;padding:18px;margin:18px 0;color:#16384c;min-width:0;overflow-wrap:anywhere;font:16px/1.6 Arial,'Malgun Gothic',sans-serif}.ml-plan-review[hidden]{display:none}.ml-plan-review h4{margin:0 0 8px;font-size:19px}.ml-plan-fields{display:grid;grid-template-columns:repeat(auto-fit,minmax(min(100%,210px),1fr));gap:14px}.ml-plan-fields label{display:grid;align-content:start;gap:6px;min-width:0}.ml-plan-fields select{box-sizing:border-box;width:100%;max-width:100%;min-height:44px;background:#fff;color:#16384c;border:1px solid #8da8b6;border-radius:8px;padding:9px;font:inherit}.ml-plan-fields select[multiple]{min-height:120px}.ml-plan-fields option{padding:4px}.ml-plan-actions{display:flex;gap:10px;flex-wrap:wrap;margin-top:16px}.ml-plan-actions button{min-height:44px;padding:10px 16px;border:1px solid #126279;border-radius:8px;background:#096b82;color:#fff;font:inherit;cursor:pointer}.ml-plan-actions button[data-plan-reset]{background:#fff;color:#16384c}html[data-design] .ml-plan-actions button{font:inherit;background:#096b82;color:#fff;border:1px solid #126279}html[data-design] .ml-plan-actions button[data-plan-reset]{background:#fff;color:#16384c}.ml-plan-review :is(button,select):focus-visible{outline:3px solid #1186ac;outline-offset:3px}.ml-plan-inherited{border-left:3px solid #238296;padding-left:10px}.ml-plan-scope{grid-column:1/-1;font-size:14px}.ml-plan-coverage{font-size:14px}`;(document.head||document.documentElement).append(s);}
})(globalThis);
