from pathlib import Path
import json,hashlib,datetime
P=Path(__file__).resolve().parent.parent
evidence=['preservation-independent-v09-v01.json','metrics-independent-v09-v01.json','help-mount-independent-v09-v01.json','ui-independent-v09-v01.json','time-scope-independent-v09-v02.json']
reports=[]
for name in evidence:
    f=P/'verification'/name;d=json.loads(f.read_text(encoding='utf8'))
    reports.append(dict(path='verification/'+name,status=d['status'],checks=len(d['checks']),sha256=hashlib.sha256(f.read_bytes()).hexdigest()))
production=['index.html','template.html','replay/metrics.js','replay/map-comparison.js','replay/replay.js','data/season-2026.json','map-data/maps.json','modeling/historical-predictions.json','modeling/predictions.json']
render=P/'verification/render-proof-v01.json';r=json.loads(render.read_text(encoding='utf8'))
out=dict(producer_id='/root/f1_verifier',producer_distinct_from_authors=True,status='INTERNAL_READY_WITH_LIMITATIONS',scope='F1 0.6.0 metrics arithmetic, missing data, bilingual meanings, routing and preserved pre-cursor logic; not entire model certification',created_at=datetime.datetime.now().isoformat(),independent_reports=reports,independent_checks=sum(x['checks'] for x in reports),independent_failures=sum(x['status']!='PASS' for x in reports),production_sha256={f:hashlib.sha256((P/f).read_bytes()).hexdigest() for f in production},root_headless_render=dict(producer_id='/root',path='verification/render-proof-v01.json',method=r['method'],checks=r['checks'],observations=len(r['observations']),errors=r['errors'],overflow_observations=sum(bool(x['overflow']) for x in r['observations']),sha256=hashlib.sha256(render.read_bytes()).hexdigest(),screenshots=['verification/render-proof-desktop-help-v01.png','verification/render-proof-mobile-help-v01.png']),findings=[dict(issue='Global metric bubble could remain across map/future route changes',resolution='Author added closeHelp(false) to stopReplay; final UI control-path test PASS'),dict(issue='Failed collection with stale arrays',resolution='Author gates arrays on source availability; independent synthetic check PASS'),dict(issue='Reviewer initial function-source slice captured helper outside function',resolution='Original v01 false FAIL preserved; narrowed v02 PASS; no app logic defect')],limitations=['Whole-race aggregate cards intentionally use completed final records; current-progress panel retains cursor cutoffs','Headless Edge render produced by root; reviewer fake DOM is not actual browser','User browser was not controlled and participant confirmation is pending','Model calibration, official future roster and all accessibility tools are outside this scope'],participant_confirmation='pending',review='verification/REVIEW-v09-metrics.ko.md')
(P/'verification/reviewer-summary-v09-v01.json').write_text(json.dumps(out,ensure_ascii=False,indent=2),encoding='utf8')
print(json.dumps(dict(status=out['status'],independent_checks=out['independent_checks'],failures=out['independent_failures'],root_render_checks=r['checks'])))
