(()=>{'use strict';function start(){
 const kicker=document.querySelector('.arcade-kicker');if(kicker)kicker.textContent='MATCHLAB / FOOTBALL';const main=document.querySelector('main');if(!main||document.querySelector('.ml-searchbox'))return;
 const isF1=!!document.getElementById('profile-data'),items=[],read=id=>JSON.parse(document.getElementById(id).textContent),ko=()=>document.documentElement.lang!=='en';
 if(isF1){const p=read('profile-data');Object.values(p.drivers).forEach(d=>items.push({name:d.full_name,extra:d.team_name,href:'#driver='+encodeURIComponent(d.id)}));Object.values(p.teams).forEach(t=>items.push({name:t.name,extra:'F1',href:'#team='+encodeURIComponent(t.id)}));}
 else Object.values(read('data').teams).forEach(t=>items.push({name:t.name,extra:t.league==='EPL'?'Premier League':'LaLiga',href:'#team='+encodeURIComponent(t.id)}));
 const box=document.createElement('section');box.className='ml-searchbox';box.innerHTML='<label class="ml-searchlabel" for="ml-search"></label><form class="ml-searchbar" role="search"><input id="ml-search" type="search" autocomplete="off" maxlength="100" aria-controls="ml-searchresults" aria-expanded="false"><button type="submit"></button></form><div id="ml-searchresults" class="ml-searchresults" hidden></div>';main.prepend(box);
 const input=box.querySelector('input'),results=box.querySelector('.ml-searchresults');
 function language(){box.querySelector('label').textContent=ko()?'기록을 탐색해 보세요':'Explore the records';input.placeholder=ko()?(isF1?'드라이버·팀 이름 검색 (영문)':'구단 이름 검색 (영문)'):(isF1?'Search drivers or teams':'Search football clubs');box.querySelector('button').textContent=ko()?'검색':'Search';}
 const normalize=s=>s.normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase();
 function show(){results.replaceChildren();const q=normalize(input.value.trim());results.hidden=!q;input.setAttribute('aria-expanded',String(!!q));if(!q)return;const matches=items.filter(t=>normalize(t.name+' '+t.extra).includes(q)).slice(0,8);if(!matches.length){const p=document.createElement('p');p.textContent=ko()?'일치하는 이름이 없습니다. 영문 이름으로 검색해 주세요.':'No matching name. Try another spelling.';results.append(p)}matches.forEach(t=>{const a=document.createElement('a');a.href=t.href;const n=document.createElement('span'),s=document.createElement('small');n.textContent=t.name;s.textContent=t.extra;a.append(n,s);a.onclick=()=>{results.hidden=true;input.setAttribute('aria-expanded','false');input.value=t.name};results.append(a)});}
 input.addEventListener('input',show);box.querySelector('form').onsubmit=e=>{e.preventDefault();show()};box.onkeydown=e=>{if(e.key==='Escape'){results.hidden=true;input.setAttribute('aria-expanded','false');input.focus()}if(e.key==='ArrowDown'&&document.activeElement===input){e.preventDefault();results.querySelector('a')?.focus()}};document.addEventListener('click',e=>{if(!box.contains(e.target)){results.hidden=true;input.setAttribute('aria-expanded','false')}});new MutationObserver(language).observe(document.documentElement,{attributes:true,attributeFilter:['lang']});language();
 }if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',start);else start();})();
