const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict');
require('../release-0.7.1/replay/metrics.js');require('./natural-analysis.js');require('./history-analysis.js');
const html=fs.readFileSync(path.join(__dirname,'../index.html'),'utf8');
const json=id=>JSON.parse(html.match(new RegExp('<script id="'+id+'" type="application/json">([\\s\\S]*?)</script>'))[1]);
const dataset=json('dataset'),history=json('f1-query-history'),saved=JSON.parse(fs.readFileSync(path.join(__dirname,'query-history.json'),'utf8'));
const hashes=JSON.parse(fs.readFileSync(path.join(__dirname,'saved-record-hashes.json'),'utf8'));const hash=x=>require('node:crypto').createHash('sha256').update(JSON.stringify(x)).digest('hex');
const api=global.MatchLabF1History,current=dataset.races.find(r=>r.session.session_key===11234),past=history.races.find(r=>r.session.session_key===9693);
let checks=0;const evidence=[];function test(name,fn){fn();checks++;evidence.push(name);console.log('PASS '+name)}
function query(q,r=current,prev){const p=api.parse(q,r,null,prev,history);assert(!p.error,q+' '+JSON.stringify(p));return {plan:p,result:api.execute(p,r,null,history)}}
test('all 24 saved record payloads are unchanged and embedded exactly',()=>{assert.deepEqual(history,saved);assert.equal(history.races.length,24);for(const r of history.races){const s=hashes.find(x=>x.session_key===r.session.session_key);assert.equal(hash(r.records),s.records);assert.equal(hash(r.session),s.session);assert.equal(r.meeting.meeting_key,r.session.meeting_key);assert.equal(r.meeting.circuit_key,r.session.circuit_key)}});
test('requested plain last-year query gives 2025 Australian result table',()=>{const {plan,result}=query('해당 그랑프리 작년 기록도 보여줘');assert.equal(plan.overview,true);assert.equal(result.results[0].year,2025);assert.equal(result.results[0].rows.length,20);assert.equal(result.results[0].rows[0].name,'Lando NORRIS');assert.equal(result.results[0].rows[0].points,25);assert(api.draw(result,false).includes('2025'));assert(api.draw(result,true).includes('Driver'))});
test('English same-GP request produces same historical records',()=>{assert.deepEqual(query('Show this Grand Prix last year records').result,query('해당 그랑프리 작년 기록도 보여줘').result)});
test('Norris and Verstappen identity survives number changes',()=>{for(const [question,name] of [['2025년 노리스 포인트 보여줘','Lando NORRIS'],['2025년 페르스타펜 포인트 보여줘','Max VERSTAPPEN']]){const {result}=query(question);const row=result.results[0].result.rows[0];assert.equal(row.name,name);const driver=past.records.drivers.find(d=>d.full_name===name),expected=past.records.session_result.find(x=>x.driver_number===driver.driver_number).points;assert.equal(row.value,expected)}});
test('same drivers compared across 2025 and 2026 using result records only',()=>{const {result}=query('작년과 올해 노리스와 페르스타펜 포인트 비교해줘');assert.deepEqual(result.results.map(x=>x.year),[2025,2026]);for(const x of result.results){const r=x.year===2025?past:current;assert.equal(x.result.rows.length,2);for(const row of x.result.rows){const driver=r.records.drivers.find(d=>d.full_name===row.name);assert.equal(row.value,r.records.session_result.find(y=>y.driver_number===driver.driver_number).points)}}});
test('missing historical lap and pit records never become zero',()=>{for(const q of ['작년 노리스 평균 랩타임 보여줘','작년 피트 진입 횟수 보여줘']){const {result}=query(q);assert.equal(result.results[0].result,null);assert.equal(result.results[0].missing.length,1);assert(api.draw(result,false).includes('수집되지 않았습니다'))}});
test('2024 per-GP record absence is explicit despite championship profiles existing',()=>{const {result}=query('재작년 기록 보여줘');assert.equal(result.results.length,0);assert.equal(result.missing[0].year,2024);assert(api.draw(result,false).includes('수집돼 있지 않습니다'))});
test('Bahrain GP identity and Sepang circuit scope are separate',()=>{const b=dataset.races.find(r=>r.session.session_key===11731);assert(b);const gp=query('작년 기록 보여줘',b).result;assert.equal(gp.results[0].name,'Bahrain Grand Prix');assert.equal(gp.results[0].venue,'Sakhir');const track=query('같은 서킷 작년 기록 보여줘',b).result;assert.equal(track.results.length,0);assert.equal(track.scope,'circuit')});
test('Barcelona rename resolves Catalunya and never Madrid by country only',()=>{const b=dataset.races.find(r=>r.session.session_key===11307),x=query('작년 기록 보여줘',b).result;assert.equal(x.results[0].name,'Spanish Grand Prix');assert.equal(x.results[0].venue,'Catalunya');const madrid={...b,meeting:{...b.meeting,meeting_name:'Madrid Grand Prix'},session:{...b.session,circuit_key:999},venue:{circuit_key:999,circuit:'Madrid'}};assert.equal(query('작년 기록 보여줘',madrid).result.results.length,0)});
test('historical ranking reversal retains selected year and metric',()=>{const before=query('작년 포인트 높은 순으로 보여줘');const after=query('반대로 보여줘',current,before.plan);assert.deepEqual(after.plan.years,[2025]);assert.equal(after.plan.plans[0].plan.metric,'points');assert.equal(after.plan.plans[0].plan.conditions.order,'asc');const rows=after.result.results[0].result.rows;assert(rows.every((x,i)=>!i||rows[i-1].value<=x.value))});
test('unsupported conditions and different named race are refused',()=>{for(const q of ['작년 최고 속도 비 오는 날만 보여줘','작년 모나코 그랑프리 포인트 보여줘','2025년 2024년 2023년 2022년 2021년 기록 보여줘'])assert(api.parse(q,current,null,null,history).error,q)});
test('unavailable year does not prevent displaying available comparison year',()=>{const result=query('2024년과 2025년 기록 비교해줘').result;assert.equal(result.results.length,1);assert.equal(result.results[0].year,2025);assert.equal(result.missing[0].year,2024)});
fs.writeFileSync(path.join(__dirname,'history-check-result.json'),JSON.stringify({checks,evidence,failures:0,method:'Saved past/current records, independent driver/result joins; no model calls'},null,2)+'\n');
