const {chromium}=require('playwright'),fs=require('node:fs'),assert=require('node:assert/strict'),path=require('node:path');
const {createServer}=require('../../server/gemini.cjs');
require('./archive-catalog.js');
(async()=>{const html=fs.readFileSync(path.join(__dirname,'../index.html'),'utf8');const json=id=>JSON.parse(html.match(new RegExp('<script id="'+id+'" type="application/json">([\\s\\S]*?)</script>'))[1]);
const D=json('dataset'),H=json('f1-query-history'),catalog=global.MatchLabF1Archive.create(D,H),before=JSON.stringify([D,H]);
assert.deepEqual(catalog.seasons,[2026,2025]);assert.equal(catalog.list(2025).length,24);assert.equal(catalog.list(2026).length,D.races.length);for(const r of H.races){assert.equal(catalog.find(r.session.session_key).records,r.records);assert.deepEqual(catalog.tabs(catalog.find(r.session.session_key)),['result','analysis','metrics'])}assert.equal(JSON.stringify([D,H]),before);
const server=createServer({key:''});await new Promise(r=>server.listen(0,'127.0.0.1',r));const base='http://127.0.0.1:'+server.address().port;
const browser=await chromium.launch({executablePath:'C:/Program Files (x86)/Microsoft/Edge/Application/msedge.exe',headless:true});const evidence=[];
try{const p=await browser.newPage(),errors=[];p.on('pageerror',e=>errors.push(e.message));
await p.goto(base+'/f1/index.html');await p.locator('#gp-year').selectOption('2025');await p.waitForURL('**year=2025');assert.equal(await p.locator('#catalog [data-race]').count(),24);assert((await p.locator('#summary').textContent()).includes('24 GP'));assert.equal(await p.locator('#gp-year-label').textContent(),'GP 시즌');
await p.locator('[data-race="9693"]').click();await p.locator('#body tbody tr').first().waitFor();assert((await p.locator('#detail h2').textContent()).includes('2025'));assert.equal(await p.locator('#body tbody tr').count(),20);assert((await p.locator('#body tbody tr').first().textContent()).includes('Lando NORRIS'));assert.equal(await p.locator('[data-tab="result"]').getAttribute('aria-pressed'),'true');for(const tab of ['map','comparison','laps','tyres','events'])assert.equal(await p.locator('[data-tab="'+tab+'"]').count(),0);
evidence.push({case:'2025 card to result',first:await p.locator('#body tbody tr').first().textContent()});
await p.locator('[data-tab="metrics"]').click();await p.locator('[data-metric-driver]').selectOption('4');const points=p.locator('.f1-metric-card').filter({has:p.locator('[data-f1-help="points"]')});assert.equal((await points.locator('.f1-metric-value').textContent()).trim(),'25');assert.equal(await p.locator('[data-metric-category] option').count(),1);await points.locator('[data-f1-help]').click();await p.locator('#f1-metric-bubble').waitFor();await p.keyboard.press('Escape');
await p.locator('[data-tab="analysis"]').click();await p.locator('#f1-question').fill('노리스 포인트 보여줘');await p.locator('.nl-form button[type="submit"]').click();assert((await p.locator('.nl-output').textContent()).includes('25'));await p.locator('#f1-question').fill('2025년과 2026년 노리스 포인트 비교해줘');await p.locator('.nl-form button[type="submit"]').click();assert.equal(await p.locator('.nl-history-season').count(),2);
await p.locator('#back').click();await p.locator('#catalog [data-race="9693"]').waitFor();assert.equal(await p.locator('#gp-year').inputValue(),'2025');assert.equal(await p.locator('#catalog [data-race]').count(),24);await p.reload();assert.equal(await p.locator('#gp-year').inputValue(),'2025');assert.equal(await p.locator('#catalog [data-race]').count(),24);
await p.goto(base+'/f1/index.html#race=9693');await p.locator('#body tbody tr').first().waitFor();assert.equal(await p.locator('#gp-year').inputValue(),'2025');assert(p.url().includes('year=2025'));
await p.locator('#language').click();assert.equal(await p.locator('#gp-year-label').textContent(),'GP season');assert((await p.locator('.gp-archive-note').textContent()).includes('Collected historical'));assert((await p.locator('#body tbody tr').first().textContent()).includes('Finished'));await p.locator('#back').click();assert.equal(await p.locator('#catalog [data-race]').count(),24);
await p.locator('#filter').selectOption('scheduled');assert.equal(await p.locator('#catalog [data-race]').count(),0);assert((await p.locator('#catalog').textContent()).includes('No Grand Prix matches'));await p.locator('#filter').selectOption('all');await p.locator('#gp-year').selectOption('2026');assert.equal(await p.locator('#catalog [data-race]').count(),25);await p.locator('[data-race="11234"]').click();await p.locator('[data-tab="map"]').waitFor();assert.equal(await p.locator('#gp-year').inputValue(),'2026');
for(const width of [390,768,1440]){await p.setViewportSize({width,height:900});for(const route of ['?year=2025','?year=2025&lang=en#race=9693']){await p.goto(base+'/f1/index.html'+route);await p.locator('#gp-year').waitFor();assert.equal(await p.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);evidence.push({width,route,overflow:false})}}
await p.goto(base+'/f1/index.html?year=2025');await p.screenshot({path:__dirname+'/archive-catalog-desktop.png',fullPage:true});await p.goto(base+'/f1/index.html?year=2025#race=9693');await p.screenshot({path:__dirname+'/archive-result-desktop.png',fullPage:true});
assert.deepEqual(errors,[]);fs.writeFileSync(__dirname+'/browser-result.json',JSON.stringify({status:'PASS',evidence,pageErrors:errors,scope:'24 archived GP records + 25 current entries; real DOM interactions; direct route/back/reload/year/language/metrics/analysis and 3 widths'},null,2)+'\n');console.log('PASS archived GP catalogue, detail, result metrics, bilingual query, back/reload/deep links, empty filters and responsive layout');
}finally{await browser.close();server.closeAllConnections();await new Promise(r=>server.close(r))}
})().catch(e=>{console.error(e);process.exitCode=1});
