'use strict';
const assert=require('node:assert/strict'),fs=require('node:fs'),http=require('node:http');
const {loadData,createServer}=require('../../server/gemini.cjs');
const {loadBundle,buildFacts,extractNews,verifyNews,publicationDates,sourceAllowed,createReportService}=require('./report.cjs');
const data=loadData(),bundle=loadBundle(),id='understat:31230',now=()=>Date.parse('2026-10-08T03:00:00Z'),checks=[];
const response=(text,groundingMetadata)=>({ok:true,status:200,json:async()=>({candidates:[{content:{parts:[{text}]},groundingMetadata}]})});
const newsText='2026-10-07 Arsenal: Fixture Player has a reported injury; availability is not confirmed.';
const grounded={groundingChunks:[{web:{uri:'https://www.arsenal.com/news/fixture-only',title:'Fixture source (not real news)'}}],groundingSupports:[{segment:{text:newsText},groundingChunkIndices:[0]}],searchEntryPoint:{renderedContent:'<p>Fixture search suggestions</p>'}};
const mock=async(url,options)=>{if(!url.includes('generativelanguage.googleapis.com')){assert(!options.headers['x-goog-api-key']);return {ok:true,status:200,text:async()=>'<script type="application/ld+json">{"datePublished":"2026-10-07T10:00:00Z"}</script>'};}const b=JSON.parse(options.body);assert(url.endsWith(':generateContent'));return b.tools?response(newsText,grounded):response(JSON.stringify({reasonIds:['form','chance','defence']}));};
async function test(name,run){await run();checks.push({name,status:'PASS'});console.log('PASS '+name);}
async function httpTest(options,fn){const s=createServer({...options,data,reportBundle:bundle,reportNow:now});await new Promise(r=>s.listen(0,'127.0.0.1',r));try{await fn('http://127.0.0.1:'+s.address().port);}finally{s.closeAllConnections();await new Promise(r=>s.close(r));}}
const post=(base,payload,extra={})=>fetch(base+'/api/report',{method:'POST',headers:{'Content-Type':'application/json',...extra},body:JSON.stringify(payload)});
(async()=>{
 await test('canonical probabilities and highest-probability final pick preserved',()=>{const f=buildFacts(data,bundle,id),p=bundle.predictions.find(p=>p.match_key===id);assert.deepEqual(f.probabilities,[p.probabilities.home,p.probabilities.draw,p.probabilities.away]);assert.equal(f.choice,'home');assert.equal(f.home.n,5);assert.equal(f.oddsIncluded,false);});
 await test('future and post-input-cutoff records cannot change report statistics',()=>{const before=buildFacts(data,bundle,id),d=structuredClone(data);d.completed.push({...d.completed[0],id:'future-fixture',home:'understat:83',away:'understat:245',date:'2026-10-09',hg:99,ag:0,hx:99,ax:0},{...d.completed[0],id:'after-game-fixture',home:'understat:83',date:'2026-10-11',hg:99});assert.deepEqual(buildFacts(d,bundle,id),before);});
 await test('missing metrics remain missing, not zero',()=>{const d=structuredClone(data);d.completed=d.completed.map(m=>({...m,hx:null,ax:null}));d.match_detail={};const f=buildFacts(d,bundle,id);assert.equal(f.home.xg,null);assert.equal(f.home.ppda,null);assert.equal(f.evidence.find(e=>e.id==='chance').edge,'unknown');});
 await test('invalid prediction identity, probabilities and cutoff rejected',()=>{for(const change of [{home_team_key:'unknown'},{probabilities:{home:1,draw:1,away:1}},{training_last_date:'2026-10-10'}]){const b=structuredClone(bundle);Object.assign(b.predictions.find(p=>p.match_key===id),change);assert.throws(()=>buildFacts(data,b,id));}});
 await test('tied probabilities produce no single favored team',()=>{const b=structuredClone(bundle);b.predictions.find(p=>p.match_key===id).probabilities={home:.4,draw:.2,away:.4};assert.equal(buildFacts(data,b,id).choice,'tie');});
 await test('no API key keeps data report and never invents injury clearance',async()=>{let calls=0;const service=createReportService({data,bundle,key:'',now,fetchImpl:()=>{calls++;throw Error();}});const r=await service.get({matchId:id,locale:'ko'});assert.equal(calls,0);assert.equal(r.narrativeStatus,'data_only');assert.equal(r.news.status,'unavailable');assert.equal(r.news.reason,'key_missing');});
 await test('concurrent identical requests coalesce and cached report makes no provider calls',async()=>{let calls=0;const service=createReportService({data,bundle,key:'test-key-do-not-return',now,fetchImpl:async(...a)=>{calls++;await new Promise(r=>setTimeout(r,20));return mock(...a);}});const input={matchId:id,locale:'ko'},[a,b]=await Promise.all([service.get(input),service.get(input)]);assert.equal(calls,3);assert.deepEqual(a,b);assert.equal(a.narrativeStatus,'ai_curated');assert.equal(a.news.status,'sourced');assert.equal((await service.get(input)).cacheHit,true);assert.equal(calls,3);assert(!JSON.stringify(a).includes('test-key-do-not-return'));});
 await test('source dates verified and unsafe redirects never fetched',async()=>{assert.deepEqual(publicationDates('<meta content="2026-10-07T01:00:00Z" property="article:published_time">'),['2026-10-07']);assert(!sourceAllowed('https://127.0.0.1/x'));assert(!sourceAllowed('https://arsenal.com.evil.example/x'));const n=extractNews(await response(newsText,grounded).json(),now());assert.equal((await verifyNews(n,mock)).items[0].dateStatus,'publisher_metadata_verified');const old=await verifyNews(n,async()=>({ok:true,status:200,text:async()=>'{"datePublished":"2025-10-07"}'}));assert.equal(old.status,'unverified');let calls=0;const blocked=await verifyNews(n,async()=>{calls++;return {status:302,headers:{get:()=> 'https://127.0.0.1/private'}};});assert.equal(calls,1);assert.equal(blocked.status,'unverified');});
 await test('unsupported AI evidence IDs fall back without changing final outcome',async()=>{const service=createReportService({data,bundle,key:'fixture',now,fetchImpl:async()=>response('{"reasonIds":["injury","made_up","bet"]}')});const r=await service.get({matchId:id,locale:'en'});assert.equal(r.narrativeStatus,'data_only');assert.equal(r.facts.choice,'home');assert.equal(r.news.status,'unverified');});
 await test('only cited statements with recent dates and safe URLs can be shown',async()=>{for(const [text,meta] of [[newsText,{}],[newsText,{...grounded,groundingChunks:[{web:{uri:'javascript:alert(1)'}}]}],[newsText.replace('2026-10-07','2025-10-07'),grounded],[newsText.replace('2026-10-07','2026-10-09'),grounded],[newsText,{...grounded,groundingSupports:[{segment:{text:'unsupported invented injury'},groundingChunkIndices:[0]}]}]]){const raw=await response(text,meta).json();assert.equal(extractNews(raw,now()).items.length,0);}assert.equal(extractNews(await response(newsText,grounded).json(),now()).items.length,1);});
 await test('quota and timeout yield usable facts with explicit unavailable status',async()=>{for(const mode of ['quota','timeout']){const service=createReportService({data,bundle,key:'fixture',now,fetchImpl:async()=>{if(mode==='quota')return {ok:false,status:429};const e=Error();e.name='TimeoutError';throw e;}});const r=await service.get({matchId:id,locale:'ko'});assert.equal(r.facts.choice,'home');assert.equal(r.narrativeError,'provider_'+mode);assert.equal(r.news.reason,'provider_'+mode);}});
 await test('old and distant fixtures do not trigger present-day injury search',async()=>{for(const timestamp of ['2026-10-11T00:00:00Z','2026-09-01T00:00:00Z']){let searches=0;const service=createReportService({data,bundle,key:'fixture',now:()=>Date.parse(timestamp),fetchImpl:async(url,o)=>{if(JSON.parse(o.body).tools)searches++;return mock(url,o);}});const r=await service.get({matchId:id,locale:'ko'});assert.equal(searches,0);assert.equal(r.news.reason,'outside_search_window');}});
 await test('HTTP report succeeds without key; extra numbers, unknown IDs, foreign origins and oversized input are rejected',()=>httpTest({key:''},async base=>{const input={matchId:id,locale:'ko'},r=await post(base,input);assert.equal(r.status,200);assert.equal((await r.json()).facts.choice,'home');assert.equal((await post(base,{...input,probabilities:[1,0,0]})).status,400);assert.equal((await post(base,{...input,matchId:'understat:9999999'})).status,404);assert.equal((await post(base,input,{Origin:'https://evil.example'})).status,403);assert.equal((await post(base,{...input,extra:'x'.repeat(2000)})).status,413);}));
 await test('Vercel pre-parsed report body and route mapping work',async()=>{process.env.VERCEL_URL='matchlab.example';process.env.GEMINI_API_KEY='';const adapter=require('../../api/handler.js');const s=http.createServer((req,res)=>{req.query={action:'report'};req.body={matchId:id,locale:'ko'};adapter(req,res);});await new Promise(r=>s.listen(0,'127.0.0.1',r));try{const r=await new Promise((resolve,reject)=>{const q=http.request({hostname:'127.0.0.1',port:s.address().port,path:'/api/handler?action=report',method:'POST',headers:{host:'matchlab.example','Content-Type':'application/json'}},r=>{let s='';r.on('data',c=>s+=c);r.on('end',()=>resolve({status:r.statusCode,json:JSON.parse(s)}));});q.on('error',reject);q.end('{}');});assert.equal(r.status,200);assert.equal(r.json.facts.choice,'home');}finally{s.closeAllConnections();await new Promise(r=>s.close(r));}});
 fs.writeFileSync(__dirname+'/checks.json',JSON.stringify({testedAt:new Date().toISOString(),method:'real local HTTP and mocked provider; not live news',checks},null,2)+'\n');
})().catch(e=>{console.error(e);process.exitCode=1;});
