/* The provider selects evidence. Canonical server facts determine all numbers and the final pick. */
(()=>{'use strict';
 const en=document.documentElement.lang==='en',tr=(ko,eng)=>en?eng:ko,locale=en?'en':'ko';
 const states=new Map(),revision=document.getElementById('match-report-module').dataset.revision||'initial';let activeKey=null;
 const el=(tag,text,cls)=>{const e=document.createElement(tag);if(text!==undefined&&text!==null)e.textContent=text;if(cls)e.className=cls;return e;};
 const cleanNews=text=>String(text).replace(/^\s*[-*]\s+/gm,'').replace(/\*\*/g,'').replace(en?/$^/:/\((?:confirmed absence|training return|doubtful|rumor)\)/gi,'').trim();
 const labels={form:tr('최근 5경기 승점','Last-five points'),attack:tr('경기당 득점','Goals per match'),defence:tr('경기당 실점','Goals conceded'),chance:tr('경기당 기대 득점','Expected goals per match'),chance_defence:tr('경기당 기대 실점','Expected goals conceded'),deep:tr('위험 지역 패스 성공','Deep completions'),deep_defence:tr('위험 지역 패스 허용','Deep completions allowed'),pressure:tr('수비 행동당 허용 패스','Passes per defensive action')};
 const meanings={form:tr('승리 3점·무승부 1점으로 최근 결과를 비교합니다.','Recent results: three points for a win and one for a draw.'),attack:tr('실제로 득점한 빈도를 비교합니다.','Compares how frequently each team scored.'),defence:tr('허용한 득점이 적을수록 수비 결과가 좋았습니다.','Fewer goals conceded indicates better defensive results.'),chance:tr('슈팅 기회의 질을 득점 기대값으로 비교합니다.','Compares the quality of shooting chances.'),chance_defence:tr('상대에게 허용한 슈팅 기회의 질을 비교합니다.','Compares the quality of chances conceded.'),deep:tr('상대 골문 가까운 위험 지역까지 연결한 패스를 비교합니다.','Compares completed passes into dangerous areas near goal.'),deep_defence:tr('위험 지역 진입 패스를 적게 허용했는지 비교합니다.','Compares how often opponents passed into dangerous areas.'),pressure:tr('값이 낮으면 상대 패스 대비 수비 행동이 더 잦았습니다. 압박 성공률은 아닙니다.','A lower value means more defensive actions per opponent pass, not a pressure success rate.')};
 function format(v){return typeof v==='number'&&Number.isFinite(v)?Number.isInteger(v)?String(v):v.toFixed(2):tr('자료 없음','No data');}
 function message(code){return ({key_missing:tr('AI 연결이 설정되지 않아 저장 지표로 보고서를 구성했습니다.','AI is not configured; this report uses saved statistics.'),provider_quota:tr('AI 사용 한도에 도달해 저장 지표를 표시합니다.','The AI quota was reached; saved statistics are shown.'),provider_auth:tr('AI 인증을 확인하지 못해 저장 지표를 표시합니다.','AI authentication failed; saved statistics are shown.'),provider_timeout:tr('AI 응답 시간이 초과돼 저장 지표를 표시합니다.','The AI request timed out; saved statistics are shown.'),outside_search_window:tr('경기일까지 14일 이내인 예정 경기만 최신 소식을 검색합니다. 지난 날짜의 경기는 현재 뉴스와 연결하지 않습니다.','Latest news is searched only for upcoming matches within 14 days. Past dates are not mixed with current news.')})[code]||tr('추가 분석을 확인하지 못했습니다. 저장된 지표와 예측은 계속 볼 수 있습니다.','Additional analysis could not be verified. Saved statistics and predictions remain available.');}
 function draw(host,r){
  host.replaceChildren();host.setAttribute('aria-busy','false');const f=r.facts;
  const top=el('div',null,'match-report-top');top.append(el('h2',tr('경기 분석 보고서','Match analysis report')),el('span',r.narrativeStatus==='ai_curated'?tr('AI 근거 정리','AI-curated evidence'):tr('저장 지표 분석','Saved-data analysis'),'match-report-tag'));host.append(top);
  host.append(el('p',f.match.home+' vs '+f.match.away+' · '+f.match.date,'match-report-subtitle'),el('p',tr('지표 기준: ','Statistics through: ')+f.cutoff,'match-report-note'));
  const choice=f.choice==='home'?f.match.home+tr(' 승리',' win'):f.choice==='away'?f.match.away+tr(' 승리',' win'):f.choice==='draw'?tr('무승부','Draw'):tr('단독 우세 없음','No sole favorite');
  const verdict=el('div',null,'match-report-verdict');verdict.append(el('span',tr('최종 예측','Final prediction')),el('h3',choice),el('p',tr('모델에서 가장 높은 확률의 결과입니다.','The highest-probability outcome in the model.')));host.append(verdict);
  const probs=el('div',null,'match-report-probs');[tr('홈승','Home win'),tr('무승부','Draw'),tr('원정승','Away win')].forEach((label,i)=>{const cell=el('div');cell.append(el('span',label),el('strong',(f.probabilities[i]*100).toFixed(1)+'%'));const bar=el('progress');bar.max=1;bar.value=f.probabilities[i];bar.setAttribute('aria-label',label);cell.append(bar);probs.append(cell);});host.append(probs);
  if(f.gap<0.10)host.append(el('p',tr('상위 두 결과의 확률 차이가 작아 접전으로 봐야 합니다.','The top two probabilities are close; this is a tight prediction.'),'match-report-warning'));
  host.append(el('h3',tr('판단에 참고한 근거','Evidence behind the preview')));
  const reasons=el('div',null,'match-report-reasons');r.reasonIds.forEach(id=>{const e=f.evidence.find(e=>e.id===id);if(!e)return;const card=el('section');card.append(el('h4',labels[id]),el('p',f.match.home+' '+format(e.home)+' · '+f.match.away+' '+format(e.away),'match-report-values'),el('p',meanings[id]));const edge=e.edge==='home'?f.match.home:e.edge==='away'?f.match.away:null;card.append(el('p',edge?edge+tr(' 쪽의 지표가 더 좋습니다.',' has the better value.'):tr('이 지표에서는 뚜렷한 차이를 확인하기 어렵습니다.','This metric does not show a clear edge.'),'match-report-edge'));reasons.append(card);});host.append(reasons);
  host.append(el('p',tr('최근 기록은 ','Recent records: ')+f.home.n+tr('경기 / ',' / ')+f.away.n+tr('경기 · 지표는 모델의 개별 가중치 기여도와 다릅니다.',' matches. Comparisons are not individual model feature contributions.'),'match-report-note'));
  const news=el('section',null,'match-report-news');news.append(el('h3',tr('부상·출전 소식','Injuries and availability')));
  if(r.news.status==='sourced'){
   news.append(el('p',tr('출처가 연결된 검색 요약입니다. 출전 확정 명단은 아니며 예측 확률에는 반영하지 않았습니다.','These search summaries have linked sources. They are not confirmed lineups and have not changed the model probabilities.')));
   r.news.items.forEach(item=>{const block=el('div',null,'match-report-news-item');block.append(el('p',cleanNews(item.text)));const links=el('div',null,'match-report-sources');item.sources.forEach(s=>{let u;try{u=new URL(s.url);}catch{return;}if(u.protocol!=='https:')return;const a=el('a',s.title);a.href=u.href;a.target='_blank';a.rel='noopener noreferrer';links.append(a);});block.append(links,el('small',tr('기사 발행일: ','Article published: ')+item.reportedDate+tr(' · 원문 날짜 확인',' · publisher date verified')));news.append(block);});
   if(r.news.suggestions){const frame=el('iframe');frame.title=tr('Google 검색 제안','Google Search suggestions');frame.setAttribute('sandbox','allow-popups allow-popups-to-escape-sandbox');frame.referrerPolicy='no-referrer';frame.srcdoc='<meta http-equiv="Content-Security-Policy" content="default-src \'none\'; style-src \'unsafe-inline\'; img-src https: data:; frame-src \'none\'; script-src \'none\'"><base target="_blank">'+r.news.suggestions;news.append(frame);}
  }else news.append(el('p',r.news.reason==='outside_search_window'?message(r.news.reason):tr('최근 부상·출전 정보를 확인하지 못했습니다. 부상자가 없다는 의미는 아닙니다.','Recent injury and availability information could not be verified. This does not mean there are no injuries.')));
  if(r.news.checkedAt)news.append(el('small',tr('검색 확인: ','Search checked: ')+new Date(r.news.checkedAt).toLocaleString(en?'en-GB':'ko-KR')));host.append(news);
  const detail=el('details'),summary=el('summary',tr('자료 기준과 분석 상태','Data cutoff and analysis status'));detail.append(summary,el('p',tr('예측 입력 기준: ','Prediction input cutoff: ')+f.cutoff+' · '+tr('보고서 생성: ','Report generated: ')+new Date(r.generatedAt).toLocaleString(en?'en-GB':'ko-KR')),el('p',tr('배당은 현재 예측에 포함되지 않았습니다. 이후 경기 기록과 최신 뉴스로 확률을 자동 보정하지 않습니다.','The current forecast excludes odds. Later results and current news do not automatically adjust its probabilities.')));
  if(r.narrativeStatus!=='ai_curated')detail.append(el('p',message(r.narrativeError)));
  detail.append(el('p',tr('현재 소식과 저장 지표의 기준 시점이 다릅니다. 최종 예측은 확정 결과가 아닙니다.','News and saved statistics have different cutoffs. The final prediction is not a guaranteed result.')));host.append(detail);
  if(r.narrativeStatus!=='ai_curated'||r.news.status!=='sourced'){const retry=el('button',tr('분석 다시 확인','Retry analysis'),'match-report-retry');retry.type='button';retry.onclick=()=>{const key=r.facts.match.id;states.delete(key);try{sessionStorage.removeItem(storageKey(key));}catch{}load(host,key);};host.append(retry);}
 }
 const storageKey=id=>'matchlab-report-0.25.0:'+revision+':'+locale+':'+id;
 async function load(host,id){
  host.replaceChildren(el('h2',tr('경기 분석 보고서','Match analysis report')),el('p',tr('지표와 예측을 정리하고, 확인 가능한 출전 소식을 찾고 있습니다…','Organizing statistics and predictions, and checking availability news…')));host.setAttribute('aria-busy','true');
  try{
   let state=states.get(id);if(state?.report&&state.report.expiresAt<=Date.now()){states.delete(id);state=null;}
   if(!state){let saved;try{saved=JSON.parse(sessionStorage.getItem(storageKey(id)));}catch{}if(saved?.version==='0.25.0'&&saved.locale===locale&&saved.facts?.match.id===id&&saved.expiresAt>Date.now()){state={report:saved};states.set(id,state);}}
   if(!state){state={};state.promise=fetch('/api/report',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({matchId:id,locale}),signal:AbortSignal.timeout(35000)}).then(async response=>{const r=await response.json();if(!response.ok)throw Error(r.error||'request_failed');if(r.version!=='0.25.0'||r.facts?.match.id!==id||r.locale!==locale)throw Error('response_mismatch');state.report=r;try{sessionStorage.setItem(storageKey(id),JSON.stringify(r));}catch{}return r;}).catch(e=>{states.delete(id);throw e;});states.set(id,state);}
   const report=state.report||await state.promise;if(host.isConnected&&activeKey===id)draw(host,report);
  }catch(e){if(!host.isConnected||activeKey!==id)return;host.setAttribute('aria-busy','false');host.replaceChildren(el('h2',tr('경기 분석 보고서','Match analysis report')),el('p',tr('보고서를 불러오지 못했습니다. 기존 승부예측은 계속 볼 수 있습니다.','The report could not be loaded. The existing prediction remains available.')));const retry=el('button',tr('다시 시도','Retry'));retry.type='button';retry.onclick=()=>load(host,id);host.append(retry);}
 }
 function update(){if(V!=='matches'||!selected){activeKey=null;return;}const existing=document.getElementById('match-ai-report');if(existing&&existing.dataset.match===selected.id){activeKey=selected.id;return;}existing?.remove();activeKey=selected.id;const host=el('article',null,'panel match-report');host.id='match-ai-report';host.dataset.match=selected.id;host.setAttribute('aria-live','polite');document.getElementById('matches').append(host);load(host,selected.id);}
 const previousMatches=renderMatches;renderMatches=function(){previousMatches();update();};const previousRender=render;render=function(){previousRender();update();};update();
})();
