const {chromium}=require('playwright'),assert=require('node:assert/strict');
(async()=>{const browser=await chromium.launch({executablePath:'C:/Program Files (x86)/Microsoft/Edge/Application/msedge.exe',headless:true});try{const page=await browser.newPage({viewport:{width:1280,height:900}}),errors=[];page.on('pageerror',e=>errors.push(e.message));await page.goto('http://127.0.0.1:8765/f1/index.html#drivers',{waitUntil:'domcontentloaded'});await page.locator('.fp-card').first().waitFor();assert.equal(await page.locator('.fp-card').count(),23);await page.waitForFunction(()=>document.querySelectorAll('.fp-card canvas[data-loaded="true"]').length===23);assert.equal(await page.locator('[data-character]').count(),23);assert.equal(await page.evaluate(()=>new Set([...document.querySelectorAll('[data-character]')].map(c=>c.toDataURL())).size),23);console.log('PASS all 23 distinct locally rendered driver characters loaded');
await page.locator('[data-profile-team]').selectOption('mclaren');assert.equal(await page.locator('.fp-card').count(),2);await page.locator('[data-profile-search]').fill('norris');assert.equal(await page.locator('.fp-card').count(),1);await page.locator('.fp-card').click();await page.waitForFunction(()=>document.querySelector('#f1-profiles h2')?.textContent==='Lando NORRIS');await page.waitForFunction(()=>document.querySelector('.fp-hero canvas')?.dataset.loaded==='true');assert.equal(await page.locator('[data-driver-metrics] .f1-metric-card').count(),8);
await page.locator('[data-pixel-toggle]').click();assert.equal(await page.locator('.fp-hero canvas').getAttribute('data-mode'),'face');await page.screenshot({path:'f1/profiles/characters-0.20.3-detail.png',fullPage:true});await page.locator('[data-pixel-toggle]').click();assert.equal(await page.locator('.fp-hero canvas').getAttribute('data-mode'),'suit');await page.locator('[data-driver-window]').selectOption('0');assert.equal(await page.locator('[data-driver-history] tbody tr').count(),16);await page.locator('[data-driver-metrics] [data-f1-help]').first().click();assert.equal(await page.locator('#f1-metric-bubble').count(),1);await page.keyboard.press('Escape');
await page.locator('.fp-teamlink a').click();await page.waitForFunction(()=>document.querySelector('#f1-profiles h2')?.textContent==='McLaren');assert.equal(await page.locator('.fp-card').count(),2);await page.locator('.f1-profile-nav a[href="#teams"]').click();await page.waitForFunction(()=>document.querySelectorAll('#f1-profiles .fp-card').length===11);await page.waitForFunction(()=>document.querySelectorAll('.fp-card canvas[data-loaded="true"]').length===11);console.log('PASS driver filters, detail metrics/help, face/suit toggle, team link and all 11 pixel logos');await page.screenshot({path:'f1/profiles/characters-0.20.3-teams.png',fullPage:true});
await page.locator('.f1-profile-nav a[href="#standings"]').click();await page.waitForFunction(()=>document.querySelectorAll('#f1-profiles tbody tr').length===34);await page.locator('#language').click();await page.waitForFunction(()=>document.querySelector('#f1-profiles h2')?.textContent==='World championship');assert((await page.locator('#f1-profiles').innerText()).includes('Season scenario'));console.log('PASS 23+11 standings rows and English language route retention');
await page.setViewportSize({width:390,height:844});await page.goto('http://127.0.0.1:8765/f1/index.html#driver=lando-norris');await page.waitForFunction(()=>document.querySelector('.fp-hero canvas')?.dataset.loaded==='true');assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);await page.screenshot({path:'f1/profiles/characters-0.20.3-mobile.png',fullPage:true});
await page.locator('.f1-profile-nav a[href="#"]').click();await page.waitForFunction(()=>!document.querySelector('#catalog').hidden);await page.goto('http://127.0.0.1:8765/f1/index.html#race=11234');await page.locator('[data-tab="result"]').click();await page.locator('#body a[href^="#driver="]').first().click();await page.locator('.fp-hero').waitFor();console.log('PASS mobile containment, GP navigation and result-to-driver link');assert.deepEqual(errors,[]);
}finally{await browser.close()}})().catch(e=>{console.error(e);process.exitCode=1});
