(function(global){
'use strict';
const esc=x=>String(x??'—').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const registry={};
function add(key,ko,en,koText,enText,category='result'){registry[key]={ko,en,koText,enText,category};}
add('final_position','최종 순위','Final position','저장된 경기 최종 분류 순위입니다. 리타이어해도 순위가 기록될 수 있으므로 상태도 함께 확인하세요.','Stored final classification position. A retired driver may still have a classified position; check status as well.');
add('points','획득 포인트','Points','이 그랑프리의 저장된 결과 포인트입니다. 시즌 누적 포인트가 아닙니다.','Points in this race’s stored result, not season-to-date points.');
add('completed_laps','완료 랩','Completed laps','최종 경기 결과의 number_of_laps입니다. 유효 랩타임 개수와 다를 수 있습니다.','The final result’s number_of_laps. This may differ from the number of valid lap-time records.');
add('final_status','최종 상태','Final status','완주, 리타이어(DNF), 미출발(DNS), 실격(DSQ)을 구분합니다. 순위만으로 완주 여부를 판단하지 마세요.','Distinguishes finished, DNF (retired), DNS (did not start), and DSQ (disqualified). Position alone does not prove a finish.');
add('grid_position','출발 순위','Starting grid position','확보된 starting_grid의 출발 순위입니다. 예선 순위와 항상 같지는 않으며 미수집이면 —입니다.','Position from acquired starting_grid records. Not necessarily the qualifying position; missing collection remains a dash.');
add('position_change','출발 대비 순위 변화','Grid-to-finish change','출발 순위−최종 순위입니다. 양수이면 최종 순위가 올라갔다는 뜻이며 실제 추월 횟수가 아닙니다. 두 순위가 모두 있을 때만 계산합니다.','Starting position minus final position. Positive means finishing higher, not a count of overtakes. Requires both positions.');
add('valid_laps','유효 랩타임 수','Valid lap-time records','lap_duration이 숫자이고 0보다 큰 기록의 개수입니다. null·0·음수는 제외합니다. 피트 아웃 랩·안전차·중단 영향은 제외하지 않습니다.','Count of finite positive lap_duration records. Null, zero and negative values are excluded. Pit-out, Safety Car and interruption-affected laps remain included.','pace');
add('best_lap','최고 랩타임','Best lap time','유효 랩타임 중 가장 짧은 시간입니다. 이 화면의 집계이며 공식 패스티스트 랩 판정은 아닙니다.','Minimum valid recorded lap duration. This display aggregate is not an official fastest-lap award determination.','pace');
add('mean_lap','평균 랩타임','Mean lap time','유효 랩타임 합계를 해당 기록 수로 나눕니다. 피트·안전차·중단·이상치도 포함하므로 순수 주행 페이스와 다릅니다.','Sum of valid durations divided by record count. Includes pit, Safety Car, interruption and outlier effects; not a clean-pace estimate.','pace');
add('lap_std','랩타임 변동성','Lap-time variability','유효 랩타임의 모집단 표준편차: √[Σ(랩타임−평균)²/n]입니다. 2개 이상일 때 표시합니다. 클수록 시간이 들쭉날쭉하지만 피트·안전차 등의 영향도 포함됩니다.','Population standard deviation: √[Σ(duration−mean)²/n], shown for at least two records. Larger values mean more spread, including pit and Safety Car effects.','pace');
for(let i=1;i<=3;i++)add('sector_'+i,`구간 ${i} 평균 시간`,`Mean sector ${i} time`,'이 드라이버의 해당 구간 양수 시간 기록만 평균합니다. 전체 랩 시간이 없어도 구간 값이 있으면 포함하며 피트·안전차 등의 영향은 제거하지 않습니다.','Mean positive recorded time for this sector. Includes partial laps when the sector is available, even if total lap duration is missing. Pit and Safety Car effects remain.','pace');
add('top_speed','최고 측정 속도','Maximum speed-trap reading','확보된 양수 st_speed 중 최댓값(km/h)입니다. 지정된 측정 지점의 속도이며 코스 전체의 절대 최고 속도를 보장하지 않습니다.','Maximum positive recorded st_speed in km/h. A speed-trap reading, not a guarantee of the absolute maximum anywhere on the circuit.','pace');
add('pit_entries','피트 진입 횟수','Pit entries','세션 시작~종료 시각 안에 기록된 피트 진입 이벤트 수입니다. 타이어 교환 횟수와 반드시 같지는 않습니다. 미수집은 0으로 바꾸지 않습니다.','Recorded pit entry events within session start/end. Not necessarily the number of tyre changes. Missing collection is not converted to zero.','pit');
add('mean_pit_lane','평균 피트레인 시간','Mean pit-lane time','확보된 양수 lane_duration의 평균이며, 없으면 기존 pit_duration 값을 사용합니다. 피트레인 이동과 정차를 포함하는 시간으로 정비 정차 시간과 다릅니다.','Mean positive lane_duration, using legacy pit_duration where unavailable. Includes pit-lane traversal and the stop; differs from stationary service time.','pit');
add('mean_stop','평균 정비 정차 시간','Mean stationary stop','확보된 양수 stop_duration만 평균합니다. 차량이 멈춰 정비한 시간이며 피트레인 이동 시간을 포함하지 않습니다. 미확보 시 —입니다. 일부 기록만 확보되면 확보한 기록의 평균이며 전체 정차 평균으로 해석하지 않습니다. OpenF1 빈 값은 경기·선수·랩이 일치하는 DHL 기반 보완 자료를 사용합니다.','Mean positive stop_duration only: stationary service time, excluding pit-lane traversal. Missing values remain a dash. Partial coverage means the average of recorded stops, not all stops. Missing OpenF1 values can use DHL-derived supplements matched by race, driver and lap.','pit');
add('stint_count','타이어 구간 수','Tyre stint records','이 드라이버의 저장된 stints 구간 개수입니다. 같은 컴파운드로 교환해도 구간이 나뉠 수 있고 피트 횟수와 1:1 대응하지 않습니다.','Number of stored stint records for this driver. Same-compound changes can create another stint; not a one-to-one pit count.','pit');
const scoreKo='저장 순위를 (출전 결과 수−순위)/(출전 결과 수−1)로 바꾼 0~1 점수입니다. 순위가 없으면 마지막 순위로 취급합니다.';
const scoreEn='Stored result score is (field size−position)/(field size−1), with missing position treated as last.';
function feature(key,ko,en,baseKo,baseEn,prior){add(key,ko,en,`${baseKo} 자료가 적을 때 기본값 ${prior}을 기록 2개만큼 섞습니다: (값 합계+2×${prior})/(기록 수+2). 단순 평균과 다릅니다.`,`${baseEn} Shrunk toward prior ${prior} with strength two: (sum+2×${prior})/(count+2), not a plain mean.`,'prediction');}
feature('recent5_finish_score','최근 5경기 순위 점수','Last-five result score',`드라이버의 이전 최대 5개 GP입니다. ${scoreKo}`,`Driver’s last up to five prior GPs. ${scoreEn}`,0.5);
feature('recent5_points','최근 5경기 보정 포인트','Last-five adjusted points','이전 최대 5개 GP의 포인트를 사용합니다.','Uses points from up to five previous GPs.',4);
feature('recent5_win_rate','최근 5경기 보정 우승 비율','Last-five adjusted win rate','이전 최대 5개 GP에서 순위 1이면 1, 그 외 0입니다.','Prior up-to-five GP indicator: first position=1, otherwise 0.',0.05);
feature('recent5_podium_rate','최근 5경기 보정 포디움 비율','Last-five adjusted podium rate','이전 최대 5개 GP에서 저장 순위 1~3이면 1입니다.','Indicator of stored positions 1–3 in up to five previous GPs.',0.15);
feature('recent5_nonfinish_rate','최근 5경기 보정 미완주 비율','Last-five adjusted non-finish rate','이전 최대 5개 GP에서 DNF·DNS·DSQ 중 하나라도 있으면 1입니다.','Indicator of any DNF, DNS or DSQ in up to five prior GPs.',0.15);
feature('season_finish_score','시즌 이전 경기 순위 점수','Season-prior result score',`대상 경기 이전의 같은 시즌 드라이버 기록입니다. ${scoreKo}`,`Driver records in the same season before the target race. ${scoreEn}`,0.5);
feature('team_recent5_finish_score','팀 최근 5GP 출전별 순위 점수','Team last-five GP entrant score',`팀의 이전 최대 5개 GP 소속 드라이버 결과 행들을 사용합니다. ${scoreKo}`,`Entrant result rows for this team’s up to five previous GPs. ${scoreEn}`,0.5);
feature('team_recent5_win_rate','팀 최근 5GP 출전별 우승 비율','Team last-five GP entrant win rate','팀의 이전 최대 5개 GP에서 소속 드라이버 행마다 우승 여부를 계산합니다. GP당 우승률이 아니라 출전 결과 행 기준입니다.','Win indicator per team entrant row across up to five previous GPs. Per-entrant rate, not wins per GP.',0.05);
feature('circuit_past_finish_score','같은 서킷 과거 순위 점수','Earlier same-circuit result score',`드라이버의 같은 circuit_key 이전 기록 전체입니다. ${scoreKo}`,`All driver records with the same circuit_key before the target. ${scoreEn}`,0.5);
feature('circuit_past_win_rate','같은 서킷 과거 우승 비율','Earlier same-circuit adjusted win rate','드라이버의 같은 circuit_key 이전 기록 전체에서 순위 1 여부를 계산합니다.','Win indicator across all earlier driver records with the same circuit_key.',0.05);
add('win_probability','우승 확률','Win probability','모델의 드라이버별 점수를 합계 100%가 되게 정규화한 실험 확률입니다. 실제 우승률로 보정된 값이나 보장된 결과가 아닙니다.','Experimental model scores normalized to sum to 100% across entrants. Not empirically calibrated win rates or guaranteed results.','prediction');
add('expected_rank','예상 순위 값','Expected rank','모델이 순위 점수를 예측한 뒤 1~출전 인원 범위로 바꾼 연속값입니다: 1+clip(예측 점수,0,1)×(인원−1). 소수·동점이 가능하며 실제 순위가 아닙니다.','Continuous model estimate: 1+clip(predicted rank score,0,1)×(field size−1). Fractions and ties are possible; not an actual finishing position.','prediction');
add('predicted_rank','예측 표시 순위','Predicted display order','예상 순위 값을 작은 순서로 정렬한 표시 순번입니다. 차량 움직임은 이 순서를 보여주는 연출이며 랩타임 예측이 아닙니다.','Display order from sorting expected rank estimates. Animated motion illustrates this order, not predicted lap times.','prediction');
add('current_rank','현재 순위','Current rank','현재 커서 이전의 최신 유효 순위 기록입니다. 없으면 랩 진행 추정에 *를 붙입니다. 끝에서만 최종 결과 순위를 사용합니다.','Latest valid position before the current cursor. Missing position uses lap inference marked *. Final result order is used only at the endpoint.');
add('current_lap','현재 랩','Current lap','현재 유효 랩 구간의 번호이며 공백에서는 마지막 완료 랩 번호를 사용합니다. 위치 기록만으로 새로운 랩을 만들지 않습니다.','Current valid lap interval number, or last completed lap during a gap. Location records do not fabricate lap numbers.');
add('current_status','현재 상태','Current status','주행·기록 공백·완주·리타이어(DNF)·미출발(DNS)·실격(DSQ)을 구분합니다.','Distinguishes racing, record gaps, finished, DNF, DNS and DSQ.');
add('current_tyre','현재 타이어','Current tyre','현재 랩이 들어가는 기록된 타이어 구간의 컴파운드입니다. 구간이 없으면 미확보입니다.','Recorded compound for the stint containing the current lap. Missing stint remains unavailable.','pit');
add('pit_so_far','현재까지 피트 진입','Pit entries so far','세션 시작 이후 현재 커서까지의 진입만 셉니다. 진행 중인 피트의 총시간은 완료 후에만 공개합니다.','Counts entries from session start through the cursor. Total duration of an ongoing pit visit is disclosed only after completion.','pit');
add('last_completed_lap','마지막 완료 랩','Last completed lap','시작 시각+랩타임이 현재 커서를 넘지 않는 가장 최근 유효 랩입니다. 진행 중인 랩의 최종 시간은 노출하지 않습니다.','Latest valid lap whose start plus duration is no later than the cursor. An active lap’s eventual duration is not exposed.','pace');
add('position_history','기록 순위 변화','Recorded rank over time','현재 커서까지 확보된 유효 순위 이벤트를 계단선으로 표시합니다. 1위가 위이며 미래 이벤트는 포함하지 않습니다.','Step chart of valid position events up to the cursor. First position is at the top; future events are excluded.');
add('completed_lap_history','완료된 랩타임','Completed lap times','현재 커서까지 완료된 최근 12개 유효 랩을 초 단위 막대로 표시합니다. 피트 아웃 랩 등도 포함됩니다.','Bars show the latest twelve completed valid laps in seconds up to the cursor, including pit-out laps.','pace');
function available(race,key){return Array.isArray(race.records?.[key])&&(!race.coverage?.[key]||race.coverage[key].status==='ok');}
function calculate(race,number,prediction){
 const n=Number(number),rec=race.records||{},result=(available(race,'session_result')?rec.session_result:[]).find(x=>x.driver_number===n),driverLaps=(available(race,'laps')?rec.laps:[]).filter(x=>x.driver_number===n),laps=driverLaps.filter(x=>Number.isFinite(x.lap_duration)&&x.lap_duration>0),times=laps.map(x=>x.lap_duration),start=Date.parse(race.session.date_start),end=Date.parse(race.session.date_end),pit=(available(race,'pit')?rec.pit:[]).filter(x=>x.driver_number===n&&Date.parse(x.date)>=start&&Date.parse(x.date)<=end),stints=(available(race,'stints')?rec.stints:[]).filter(x=>x.driver_number===n),mean=xs=>xs.length?xs.reduce((a,b)=>a+b,0)/xs.length:null,avg=mean(times),lane=pit.map(x=>x.lane_duration??x.pit_duration).filter(x=>Number.isFinite(x)&&x>0),stop=pit.map(x=>x.stop_duration).filter(x=>Number.isFinite(x)&&x>0),rows=[];
 function row(key,value,unit=''){rows.push({key,value,unit,category:registry[key]?.category||'prediction'});}
 if(race.state==='completed'){row('final_position',Number.isFinite(result?.position)?result.position:null);row('points',Number.isFinite(result?.points)?result.points:null);row('completed_laps',Number.isFinite(result?.number_of_laps)?result.number_of_laps:null);row('final_status',result?(result.dns?'DNS':result.dsq?'DSQ':result.dnf?'DNF':'FINISHED'):null);const grid=(rec.starting_grid||[]).find(x=>x.driver_number===n),gridPos=available(race,'starting_grid')&&Number.isFinite(grid?.position)?grid.position:null;row('grid_position',gridPos);row('position_change',gridPos!==null&&Number.isFinite(result?.position)?gridPos-result.position:null);row('valid_laps',available(race,'laps')?times.length:null);row('best_lap',times.length?Math.min(...times):null,'s');row('mean_lap',avg,'s');row('lap_std',times.length>=2?Math.sqrt(mean(times.map(x=>(x-avg)**2))):null,'s');for(let i=1;i<=3;i++)row('sector_'+i,mean(driverLaps.map(x=>x['duration_sector_'+i]).filter(x=>Number.isFinite(x)&&x>0)),'s');const speeds=driverLaps.map(x=>x.st_speed).filter(x=>Number.isFinite(x)&&x>0);row('top_speed',speeds.length?Math.max(...speeds):null,'km/h');row('pit_entries',available(race,'pit')?pit.length:null);row('mean_pit_lane',mean(lane),'s');row('mean_stop',mean(stop),'s');rows[rows.length-1].coverage={recorded:stop.length,total:pit.length};row('stint_count',available(race,'stints')?stints.length:null);}
 const pred=prediction?.drivers?.find(x=>x.driver_number===n);if(pred){Object.keys(pred.features||{}).forEach(k=>row(k,Number.isFinite(pred.features[k])?pred.features[k]:null));row('win_probability',Number.isFinite(pred.win_probability)?pred.win_probability:null,'%');row('expected_rank',Number.isFinite(pred.expected_rank)?pred.expected_rank:null);}
 return rows;
}
function buttonHtml(key,locale='ko',label){const r=registry[key],en=locale==='en',text=label||(r?(en?r.en:r.ko):key);return `<button type="button" class="f1-metric-help" data-f1-help="${esc(key)}" data-help-locale="${en?'en':'ko'}" aria-expanded="false" aria-controls="f1-metric-bubble"><span>${esc(text)}</span><span aria-hidden="true">ⓘ</span></button>`;}
function placeBubble(anchor,size,viewport){const margin=8,width=Math.min(size.width,Math.max(1,viewport.width-16)),height=Math.min(size.height,Math.max(1,viewport.height-16)),above=anchor.bottom+height+8>viewport.height-8&&anchor.top-height-8>=8;return {left:Math.max(margin,Math.min(anchor.left,viewport.width-width-margin)),top:Math.max(margin,Math.min(above?anchor.top-height-8:anchor.bottom+8,viewport.height-height-margin)),above,width,height};}
let bubble=null,trigger=null,installed=false;
function closeHelp(restore=true){if(!bubble)return;const old=trigger;bubble.remove();bubble=null;trigger=null;old?.setAttribute('aria-expanded','false');if(restore&&old?.isConnected)old.focus();}
function reposition(){if(!bubble||!trigger?.isConnected){closeHelp(false);return;}const a=trigger.getBoundingClientRect(),b=bubble.getBoundingClientRect(),v={width:global.innerWidth,height:global.innerHeight},p=placeBubble(a,b,v);bubble.style.left=p.left+'px';bubble.style.top=p.top+'px';bubble.dataset.side=p.above?'above':'below';bubble.style.setProperty('--arrow-x',Math.max(12,Math.min(p.width-20,a.left+a.width/2-p.left))+'px');}
function openHelp(button){const key=button.dataset.f1Help,r=registry[key];if(!r)return;if(trigger===button){closeHelp();return;}closeHelp(false);trigger=button;const en=button.dataset.helpLocale==='en';bubble=document.createElement('div');bubble.id='f1-metric-bubble';bubble.className='f1-metric-bubble';bubble.setAttribute('role','dialog');bubble.setAttribute('aria-modal','false');bubble.setAttribute('aria-labelledby','f1-metric-bubble-title');bubble.tabIndex=-1;bubble.innerHTML=`<div class="f1-bubble-head"><strong id="f1-metric-bubble-title">${esc(en?r.en:r.ko)}</strong><button type="button" data-f1-help-close>${en?'Close':'닫기'}</button></div><p>${esc(en?r.enText:r.koText)}</p>`;document.body.append(bubble);button.setAttribute('aria-expanded','true');bubble.querySelector('[data-f1-help-close]').onclick=()=>closeHelp();reposition();bubble.focus();}
function installHelp(){if(installed||typeof document==='undefined')return;installed=true;const style=document.createElement('style');style.id='f1-metric-help-styles';style.textContent=styles().replace(/^<style>|<\/style>$/g,'');(document.head||document.body).append(style);document.addEventListener('click',e=>{const b=e.target.closest?.('[data-f1-help]');if(b){openHelp(b);return;}if(bubble&&!bubble.contains(e.target)&&!trigger?.contains(e.target))closeHelp(false);});document.addEventListener('keydown',e=>{if(e.key==='Escape'&&bubble){e.preventDefault();closeHelp();}});global.addEventListener?.('resize',reposition);global.addEventListener?.('scroll',reposition,true);}
function styles(){return `<style>.f1-metrics-grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(min(100%,180px),1fr));gap:12px}.f1-metric-card{min-width:0;border:2px solid #b4c4a0;background:#eef0d9;padding:16px;box-shadow:3px 3px #cbd4ba}.f1-metric-value{display:block;margin:12px 0 2px;font-size:28px;font-weight:900;white-space:nowrap;line-height:1.3}.f1-metric-value.is-text{white-space:normal;word-break:keep-all;overflow-wrap:anywhere;font-size:20px}.f1-metric-help{display:inline-flex;gap:8px;align-items:center;justify-content:space-between;min-height:44px;max-width:100%;background:transparent;border:0;padding:4px 0;text-align:left;font:inherit;font-size:16px;line-height:1.5;color:#162e37;cursor:pointer;white-space:normal;word-break:keep-all;overflow-wrap:anywhere}.f1-metric-help span:first-child{min-width:0}.f1-metric-help span:last-child{flex-shrink:0}.f1-metric-bubble{position:fixed;z-index:10000;width:min(360px,calc(100vw - 16px));max-height:calc(100dvh - 16px);overflow:auto;padding:16px;background:#fff9e9;color:#162e37;border:2px solid #162e37;box-shadow:4px 4px #a6b893;font:16px/1.6 system-ui,"Malgun Gothic",sans-serif;word-break:keep-all;overflow-wrap:anywhere}.f1-bubble-head{display:flex;align-items:center;justify-content:space-between;gap:12px}.f1-bubble-head strong{min-width:0}.f1-bubble-head button{flex-shrink:0;min-height:44px;font:inherit}.f1-metric-bubble p{margin:10px 0 0}.f1-metrics-controls{display:flex;gap:12px;flex-wrap:wrap;align-items:center;margin:0 0 20px}.f1-metrics-controls select{max-width:100%;min-width:0}.f1-metric-card small{display:block;color:#52666d}</style>`;}
function mount(container,race,prediction,{locale='ko'}={}){
 installHelp();const en=locale==='en',drivers=race.state==='completed'?(race.records.drivers||[]):(prediction?.drivers||[]),categories={all:en?'All':'전체',result:en?'Race result':'경기 결과',pace:en?'Lap pace':'랩 페이스',pit:en?'Tyres & pits':'타이어 · 피트',prediction:en?'Pre-race model inputs':'경기 전 예측 지표'};
 container.innerHTML=styles()+`<div class="f1-metrics-controls"><label>${en?'Driver':'드라이버'} <select data-metric-driver>${drivers.map(d=>`<option value="${d.driver_number}">${esc(d.full_name||d.name||d.driver_number)}</option>`).join('')}</select></label><label>${en?'Category':'항목'} <select data-metric-category>${Object.entries(categories).map(([k,v])=>`<option value="${k}">${v}</option>`).join('')}</select></label></div><div class="f1-metrics-grid" data-metric-cards></div>`;
 const select=container.querySelector('[data-metric-driver]'),filter=container.querySelector('[data-metric-category]'),cards=container.querySelector('[data-metric-cards]');select.value=String(drivers[0]?.driver_number||'');filter.value='all';
 function render(){closeHelp(false);const rows=calculate(race,select.value,prediction).filter(x=>filter.value==='all'||x.category===filter.value);cards.innerHTML=rows.map(row=>{let v=row.value===null?'—':typeof row.value==='number'?(row.unit==='%'?(row.value*100).toFixed(1)+'%':Number.isInteger(row.value)?row.value:String(Number(row.value.toFixed(3)))):row.value;if(row.key==='final_status'&&!en)v={FINISHED:'완주',DNF:'리타이어',DNS:'미출발',DSQ:'실격'}[v]||v;return `<article class="f1-metric-card">${buttonHtml(row.key,locale)}<strong class="f1-metric-value${typeof row.value==='string'?' is-text':''}">${esc(v)}${row.unit&&row.unit!=='%'&&row.value!==null?' '+esc(row.unit):''}</strong><small>${row.key==='mean_stop'?(row.coverage.total===0?(en?'No pit entries':'피트 진입 없음'):row.coverage.recorded===0?(en?'Stop time not recorded':'정차 시간 기록 없음'):(en?'Recorded stops: ':'확보한 정차 기록 ')+row.coverage.recorded+'/'+row.coverage.total+(row.coverage.recorded<row.coverage.total?(en?' · partial average':' · 일부 기록 평균'):'')):row.value===null?(en?'Not available':'자료 미확보'):row.category==='prediction'?(en?'Pre-race input / estimate':'경기 전 입력 · 추정'):en?'Completed race record':'종료 경기 기록'}</small></article>`}).join('')||`<p>${en?'No metrics in this category.':'이 항목의 자료가 없습니다.'}</p>`;}
 select.addEventListener('change',render);filter.addEventListener('change',render);render();return {destroy(){closeHelp(false);select.removeEventListener('change',render);filter.removeEventListener('change',render);container.replaceChildren()}};
}
if(typeof document!=='undefined'&&document.body)installHelp();
global.MatchLabF1Metrics={registry,calculate,buttonHtml,placeBubble,installHelp,closeHelp,mount,styles};
})(typeof window!=='undefined'?window:globalThis);
