const {chromium}=require('C:/Users/Administrator/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');const fs=require('fs'),path=require('path'),assert=require('assert');let b;
(async()=>{b=await chromium.launch({executablePath:'C:/Program Files (x86)/Microsoft/Edge/Application/msedge.exe',headless:true});const page=await b.newPage();page.setDefaultTimeout(12000);const f=JSON.parse(fs.readFileSync(path.join(__dirname,'fixture.json'),'utf8'));const errors=[];page.on('pageerror',e=>errors.push(e.message));await page.setContent('<style>*{box-sizing:border-box}body{font:16px/1.6 system-ui;margin:12px;color:#162e37;background:#e8efdc}button{min-height:44px;font:inherit}.table-wrap{overflow:auto}#host{padding:16px;background:#fff9e9}</style><main id="host"></main>');await page.addScriptTag({path:path.join(__dirname,'../replay/metrics.js')});await page.addScriptTag({path:path.join(__dirname,'../replay/natural-analysis.js')});let checks=0;
for(const en of [false,true])for(const width of [320,375,768,1280]){await page.setViewportSize({width,height:850});await page.evaluate(({f,en})=>MatchLabF1Natural.mount(document.getElementById('host'),f.race,f.pred,{locale:en?'en':'ko'}),{f,en});async function ask(q){await page.locator('textarea').fill(q);await page.getByRole('button',{name:en?'Show results':'결과 보기',exact:true}).click();}
await ask(en?'Norris mean stationary stop':'노리스 평균 정차 시간');assert(await page.locator('.nl-value-card').count()===1);assert((await page.locator('.nl-big').innerText()).includes('2.75'));checks+=2;
await ask(en?'Norris average lap time laps 1-20':'노리스 1~20랩 평균 랩타임');assert((await page.locator('.nl-condition').innerText()).includes('1–20'));await page.locator('[data-f1-help=mean_lap]').click();assert(await page.getByRole('dialog').isVisible());await page.keyboard.press('Escape');checks+=2;
await ask(en?'Top speed top 5':'최고 속도 상위 5명');assert(await page.locator('.nl-bar-row').count()===5);checks++;
await ask(en?'Norris best lap time and maximum speed':'노리스 최고 랩타임과 최고 속도');assert(await page.locator('.nl-section').count()===2);checks++;
await ask(en?'Pit stop time under 3 seconds':'평균 정차 시간 3초 미만인 선수');assert((await page.locator('.nl-condition').innerText()).includes('< 3'));assert(await page.locator('.nl-bar-row').count()>1);checks+=2;
assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1));checks++;
if(width===375&&!en)await page.screenshot({path:path.join(__dirname,'conditions-mobile-v01.png')});
await ask('최고 속도 3초 미만');assert(await page.locator('.nl-bar-row').count()===0);assert((await page.getByRole('status').innerText()).includes(en?'conditions':'조건'));checks++;
}
assert(errors.length===0);fs.writeFileSync(path.join(__dirname,'conditions-render-v01.json'),JSON.stringify({status:'PASS',checks,errors,scope:'Real isolated component, KO/EN at 320/375/768/1280px; query/cards/conditions/help/overflow',participant_confirmation:'pending'},null,2));console.log('PASS UI',checks);await b.close()})().catch(async e=>{console.error(e);await b?.close();process.exitCode=1});
