const {chromium}=require('playwright'),fs=require('node:fs'),assert=require('node:assert/strict');const {createServer}=require('../../server/gemini.cjs');
(async()=>{const server=createServer({key:''});await new Promise(r=>server.listen(0,'127.0.0.1',r));const base='http://127.0.0.1:'+server.address().port;const b=await chromium.launch({executablePath:'C:/Program Files (x86)/Microsoft/Edge/Application/msedge.exe',headless:true});let checks=[];
try{const p=await b.newPage();let errors=[];p.on('pageerror',e=>errors.push(e.message));
for(const lang of ['ko','en'])for(const width of [390,768,1440]){await p.setViewportSize({width,height:900});await p.goto(base+'/f1/index.html?year=2026&lang='+lang+'#race=11234');await p.locator('[data-tab=tyres]').click();const actual=p.locator('#body [data-tyre-help]').first();assert(await actual.count());await actual.click();const bubble=p.locator('#f1-tyre-bubble');await bubble.waitFor();assert((await bubble.innerText()).includes(lang==='ko'?'마른 노면':'dry tracks'));assert((await bubble.locator('a').getAttribute('href')).startsWith('https://www.formula1.com/'));await p.keyboard.press('Escape');assert.equal(await bubble.count(),0);assert(await actual.evaluate(e=>document.activeElement===e));
// Dedicated controls exercise all five compounds, including wet compounds absent from this GP.
await p.evaluate(lang=>{const area=document.createElement('section');area.id='tyre-test-controls';area.innerHTML=Object.keys(MatchLabF1Tyres.tyres).map(k=>MatchLabF1Tyres.buttonHtml(k,lang,'test-'+k)).join('');document.querySelector('#body').prepend(area);},lang);
for(const key of ['SOFT','MEDIUM','HARD','INTERMEDIATE','WET']){const btn=p.locator('#tyre-test-controls [data-tyre-help='+key+']');await btn.focus();await p.keyboard.press('Enter');await bubble.waitFor();const rect=await bubble.boundingBox();assert(rect.x>=7&&rect.y>=7&&rect.x+rect.width<=width-7&&rect.y+rect.height<=901);const text=await bubble.innerText();assert(text.includes(lang==='ko'?'공식 설명':'Official guide'));const css=await bubble.evaluate(e=>getComputedStyle(e).fontSize);assert.equal(css,'16px');if(key==='INTERMEDIATE'&&width===390)await p.screenshot({path:__dirname+'/tyre-'+lang+'-390.png'});await bubble.locator('button').click();assert.equal(await bubble.count(),0);checks.push({lang,width,key,rect});}
const btn=p.locator('#tyre-test-controls [data-tyre-help=SOFT]');await btn.click();await p.locator('.detail-head h2').click();assert.equal(await bubble.count(),0);assert.equal(await p.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);
await p.locator('[data-tab=map]').click();await p.locator('[data-map-driver]').selectOption('1');await p.locator('[data-map-seek]').evaluate(e=>{e.value='0.1';e.dispatchEvent(new Event('input',{bubbles:true}));});const live=p.locator('[data-tyre-anchor="dashboard-current"]');assert.equal(await live.count(),1,await p.locator('.f1-driver-dashboard').innerText());await live.click();await bubble.waitFor();const compound=await live.getAttribute('data-tyre-help');await p.locator('[data-map-seek]').evaluate(e=>{e.value='0.10001';e.dispatchEvent(new Event('input',{bubbles:true}));});await p.waitForTimeout(100);assert.equal(await bubble.count(),1,'Popover lost on dashboard redraw');assert.equal(await p.locator('[data-tyre-anchor="dashboard-current"]').getAttribute('aria-expanded'),'true');await p.keyboard.press('Escape');checks.push({lang,width,actualReplayCompound:compound,redraw:'PASS'});
}assert.deepEqual(errors,[]);const html=fs.readFileSync(__dirname+'/../index.html','utf8'),before=fs.readFileSync(__dirname+'/index-before.html','utf8');let payloads=0;for(const m of before.matchAll(/<script[^>]*type="application\/json"[^>]*>[\s\S]*?<\/script>/g)){assert(html.includes(m[0]));payloads++;}fs.writeFileSync(__dirname+'/tyre-browser-result.json',JSON.stringify({status:'PASS',checks,unchangedPayloads:payloads,pageErrors:errors},null,2));console.log('PASS: five compounds, both languages, 390/768/1440px, keyboard/click/outside-close, actual stints, live dashboard redraw, JSON preserved');
}finally{await b.close();server.closeAllConnections();await new Promise(r=>server.close(r));}})().catch(e=>{console.error(e);process.exitCode=1});
