/* Official-source tyre summaries. Explanations never change recorded compound data. */
(function(g){'use strict';
const sources={slick:'https://www.formula1.com/en/latest/article/the-beginners-guide-to-f1-tyres.61SvF0Kfg29UR2SPhakDqd',rain:'https://www.pirelli.com/tyres/en-ww/motorsport/car/formula-1'};
const tyres={
 SOFT:{ko:'소프트',en:'Soft',color:'#c33c36',koText:'마른 노면용. 접지력이 높아 짧은 구간에서 속도를 내기 좋지만, 성능이 빨리 떨어지는 편입니다. 예선이나 짧은 주행 구간에 활용합니다.',enText:'For dry tracks. Offers high grip for short bursts, but usually loses performance sooner. Useful for qualifying or short stints.',source:sources.slick},
 MEDIUM:{ko:'미디엄',en:'Medium',color:'#a77708',koText:'마른 노면용. 속도와 타이어 수명의 균형을 노리는 중간 성격입니다. 레이스에서 비교적 긴 구간을 안정적으로 달릴 때 활용합니다.',enText:'For dry tracks. Balances pace and tyre life between soft and hard. Useful for sustained race stints.',source:sources.slick},
 HARD:{ko:'하드',en:'Hard',color:'#657184',koText:'마른 노면용. 소프트보다 접지력은 낮지만 오래 버티는 편입니다. 긴 주행 구간과 타이어 교체 횟수를 줄이는 전략에 활용합니다.',enText:'For dry tracks. Generally offers less grip than soft but lasts longer. Useful for long stints and strategies with fewer tyre changes.',source:sources.slick},
 INTERMEDIATE:{ko:'인터미디어트',en:'Intermediate',color:'#257246',koText:'비가 오거나 노면이 젖었을 때 사용하는 타이어입니다. 물이 고이지 않은 젖은 노면이나, 비가 그쳐 트랙이 마르는 과정에 적합합니다.',enText:'A rain tyre for wet tracks without standing water. Also suits a drying track as conditions transition towards slick tyres.',source:sources.rain},
 WET:{ko:'웨트',en:'Full wet',color:'#2865ac',koText:'비가 많고 노면에 물이 많은 상황에서 사용합니다. 배수 성능이 높아 물 위에서 미끄러지는 현상을 줄이지만, 폭우에는 시야 문제로 경기가 중단될 수 있습니다.',enText:'For heavy rain and water on the track. Disperses water to reduce aquaplaning, though poor visibility can still cause a race stoppage.',source:sources.rain}
};
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function buttonHtml(compound,locale='ko',anchor=''){const key=String(compound||'').toUpperCase(),t=tyres[key],en=locale===true||locale==='en';if(!t)return esc(compound||'—');return `<button type="button" class="f1-tyre-help" data-tyre-help="${key}" data-tyre-locale="${en?'en':'ko'}" data-tyre-anchor="${esc(anchor)}" aria-expanded="false" aria-controls="f1-tyre-bubble" aria-label="${esc((en?t.en:t.ko)+(en?' tyre characteristics':' 타이어 특성 보기'))}"><span class="f1-tyre-dot" style="--tyre-color:${t.color}" aria-hidden="true"></span><span>${esc(en?t.en:t.ko)}</span><span aria-hidden="true">ⓘ</span></button>`;}
g.MatchLabF1Tyres={tyres,buttonHtml};
if(typeof document==='undefined')return;
const style=document.createElement('style');style.id='f1-tyre-help-styles';style.textContent=`.f1-tyre-help{display:inline-flex;align-items:center;justify-content:center;gap:6px;min-width:44px;min-height:44px;padding:6px 9px;border:1px solid #a6b8c9;border-radius:9px;background:#fff;color:#16384c;font:inherit;font-size:14px;line-height:1.4;white-space:normal;max-width:100%;cursor:pointer;vertical-align:middle}.f1-tyre-help:focus-visible{outline:3px solid #007d96;outline-offset:2px}.f1-tyre-dot{width:11px;height:11px;flex:none;background:var(--tyre-color);border-radius:50%}.f1-tyre-bubble{position:fixed;z-index:10000;box-sizing:border-box;width:min(340px,calc(100vw - 16px));max-height:calc(100dvh - 16px);overflow:auto;padding:16px;border:2px solid #37667a;border-radius:14px;background:#fff;box-shadow:0 6px 24px #102c4533;color:#16384c;font-family:Arial,'Malgun Gothic',sans-serif;font-size:16px;line-height:1.65;overflow-wrap:anywhere}.f1-tyre-bubble-head{display:flex;align-items:center;justify-content:space-between;gap:12px}.f1-tyre-bubble-head strong{font-size:18px;min-width:0}.f1-tyre-bubble-head button{min-height:44px;min-width:44px;padding:4px 8px;border:1px solid #a6b8c9;border-radius:8px;background:#f4f8fb;color:#16384c;font:inherit;cursor:pointer}.f1-tyre-bubble p{margin:10px 0}.f1-tyre-bubble small{display:block;font-size:13px;color:#405b69}.f1-tyre-bubble a{display:inline-block;padding-top:5px;color:#066878;text-decoration:underline}.stint-label .f1-tyre-help{margin-right:5px}.f1-driver-text .f1-tyre-help{font-size:16px}`;
(document.head||document.documentElement).append(style);
let bubble=null,trigger=null,key=null,anchor=null,locale=null,scheduled=0;
function findTrigger(){if(trigger?.isConnected)return trigger;return Array.from(document.querySelectorAll('[data-tyre-help]')).find(b=>b.dataset.tyreAnchor===anchor&&b.dataset.tyreHelp===key&&b.dataset.tyreLocale===locale);}
function close(restore=true){if(!bubble)return;const old=findTrigger();bubble.remove();bubble=null;old?.setAttribute('aria-expanded','false');trigger=null;if(restore)old?.focus();}
function place(){if(!bubble)return;trigger=findTrigger();if(!trigger){close(false);return;}trigger.setAttribute('aria-expanded','true');const a=trigger.getBoundingClientRect(),b=bubble.getBoundingClientRect(),w=g.innerWidth,h=g.innerHeight;const top=a.bottom+8+b.height<=h-8?a.bottom+8:a.top-b.height-8;bubble.style.left=Math.max(8,Math.min(a.left,w-b.width-8))+'px';bubble.style.top=Math.max(8,Math.min(top,h-b.height-8))+'px';}
function open(b){if(trigger===b&&bubble){close();return;}close(false);trigger=b;key=b.dataset.tyreHelp;anchor=b.dataset.tyreAnchor;locale=b.dataset.tyreLocale;const en=locale==='en',t=tyres[key];if(!t)return;bubble=document.createElement('div');bubble.id='f1-tyre-bubble';bubble.className='f1-tyre-bubble';bubble.setAttribute('role','dialog');bubble.setAttribute('aria-modal','false');bubble.setAttribute('aria-labelledby','f1-tyre-title');bubble.tabIndex=-1;bubble.innerHTML=`<div class="f1-tyre-bubble-head"><strong id="f1-tyre-title">${esc(en?t.en:t.ko)}</strong><button type="button">${en?'Close':'닫기'}</button></div><p>${esc(en?t.enText:t.koText)}</p>${['SOFT','MEDIUM','HARD'].includes(key)?`<small>${en?'These names are relative to the three slick compounds selected for this GP. Performance depends on the track and conditions.':'소프트·미디엄·하드는 해당 GP에 선택된 세 종류의 상대 구분입니다. 실제 성능은 노면과 조건에 따라 달라집니다.'}</small>`:''}<a href="${t.source}" target="_blank" rel="noopener noreferrer">${en?'Official guide':'공식 설명'}</a>`;document.body.append(bubble);bubble.querySelector('button').onclick=()=>close();place();bubble.focus();}
document.addEventListener('click',e=>{const b=e.target.closest?.('[data-tyre-help]');if(b){open(b);return;}if(bubble&&!bubble.contains(e.target))close(false);});
document.addEventListener('keydown',e=>{if(e.key==='Escape'&&bubble){e.preventDefault();close();}});g.addEventListener('resize',place);g.addEventListener('scroll',place,true);
new MutationObserver(()=>{if(bubble&&!scheduled)scheduled=g.requestAnimationFrame(()=>{scheduled=0;place();});}).observe(document.documentElement,{childList:true,subtree:true});
})(globalThis);
