// Calculation/navigation checks using a DOM stub; browser UI remains unverified.
const fs=require('fs'),vm=require('vm'),assert=require('assert');
const html=fs.readFileSync(__dirname+'/index.html','utf8');
const json=html.match(/<script id="data" type="application\/json">([\s\S]*?)<\/script>/)[1];
const data=JSON.parse(json),code=html.match(/<script>([\s\S]*?)<\/script>/)[1];
const nodes=new Map(),events={};
class Node {
 constructor(){this.value='';this.dataset={};this.hidden=false;this.textContent='';this.checked=false;const classes=new Set();this.classList={toggle(name,on){if(on)classes.add(name);else classes.delete(name)},contains(name){return classes.has(name)}}}
 set innerHTML(s){this.html=s;if(s.includes('<option')){this.options=[...s.matchAll(/<option value="([^"]+)"/g)].map(m=>m[1]);this.value=this.options[0]||''}}
 get innerHTML(){return this.html||''}
 querySelectorAll(selector){let attr=selector.includes('data-season')?'season':'id';return [...this.innerHTML.matchAll(new RegExp('data-'+attr+'="([^"]+)"','g'))].map(m=>{let n=new Node();n.dataset[attr]=m[1];return n})}
}
const get=id=>{if(!nodes.has(id))nodes.set(id,new Node());return nodes.get(id)};
get('data').textContent=json;get('season').value='2026/27';get('venue').value='all';get('resultfilter').value='all';get('rangefilter').value='season';get('metricgroup').value='all';
const nav=['matches','team','league'].map(view=>{let n=new Node();n.dataset.view=view;return n});
const context=vm.createContext({document:{getElementById:get,querySelectorAll(){return nav},addEventListener(name,fn){events[name]=fn}},window:{location:{hash:''},addEventListener(name,fn){events[name]=fn}},console});
vm.runInContext(code,context);
let checks=0;function test(name,fn){fn();checks++;console.log('PASS '+name)}
function run(code){return vm.runInContext(code,context)}
test('56 observed logo URLs inserted; no image downloads required',()=>{assert.strictEqual(Object.keys(data.teams).length,56);assert(Object.values(data.teams).every(t=>t.logo&&t.logo.startsWith('https://cdn.statmuse.com/')))});
test('logos are labelled links and include load-failure fallback',()=>{let b=run('badge("understat:83",true)');assert(b.includes('data-team="understat:83"'));assert(b.includes('aria-label="Arsenal 종합 정보 보기"'));assert(b.includes('<img'));assert(b.includes('nextElementSibling.hidden=false'));assert(b.includes('loading="lazy"'))});
test('fixture card keeps logo links outside analysis button',()=>{const buttons=[...get('fixtures').innerHTML.matchAll(/<button[^>]*>([\s\S]*?)<\/button>/g)];assert(buttons.length>0);assert(buttons.every(b=>!b[1].includes('<a')));assert(get('fixtures').innerHTML.includes('<article'));assert(get('comparison').innerHTML.includes('Arsenal'))});
test('delegated logo click opens exact team profile',()=>{let prevented=false;events.click({target:{closest(){return {dataset:{team:'understat:245'}}}},preventDefault(){prevented=true}});assert(prevented);assert.strictEqual(get('teamselect').value,'understat:245');assert(get('teamcontent').innerHTML.includes('Leeds'));assert.strictEqual(get('matches').hidden,true)});
test('cross-league team logo updates league and profile',()=>{run('openTeam("understat:148")');assert.strictEqual(get('league').value,'La_liga');assert.strictEqual(get('teamselect').value,'understat:148');assert(get('teamcontent').innerHTML.includes('Barcelona'))});
test('profile exposes all four seasons, records and season links',()=>{assert(['2023/24','2024/25','2025/26','2026/27'].every(s=>get('teamcontent').innerHTML.includes('data-season="'+s+'"')));assert(get('teamcontent').innerHTML.includes('경기당 승점'));assert(get('teamcontent').innerHTML.includes('홈'));assert(get('teamcontent').innerHTML.includes('원정'))});
test('season records independently sum raw score fields',()=>{run('openTeam("understat:83")');get('season').value='2023/24';get('season').onchange();const ms=data.completed.filter(m=>m.season==='2023/24'&&(m.home==='understat:83'||m.away==='understat:83'));let p=0,gf=0,ga=0;ms.forEach(m=>{let f=m.home==='understat:83'?m.hg:m.ag,a=m.home==='understat:83'?m.ag:m.hg;gf+=f;ga+=a;p+=f>a?3:f===a?1:0});let s=run('calc("understat:83",games("understat:83","2023/24"))');assert.strictEqual(s.n,38);assert.strictEqual(s.p,p);assert.strictEqual(s.gf,gf);assert.strictEqual(s.ga,ga);assert.strictEqual((get('teamcontent').innerHTML.match(/<small class="muted">202[34]-/g)||[]).length,38)});
test('venue filter exposes only 19 home games in completed season',()=>{get('venue').value='home';get('venue').onchange();let ms=run('filterHistory("understat:83",games("understat:83","2023/24"))');assert.strictEqual(ms.length,19);assert(ms.every(m=>m.home==='understat:83'));assert(get('teamcontent').innerHTML.includes('19 / 19경기'))});
test('win filter returns only actual winning results',()=>{get('resultfilter').value='win';get('resultfilter').onchange();let ms=run('filterHistory("understat:83",games("understat:83","2023/24"))');assert(ms.length>0);assert(ms.every(m=>m.hg>m.ag))});
test('empty season stays missing instead of invented zero season',()=>{get('season').value='1900/01';get('season').onchange();assert(get('teamcontent').innerHTML.includes('선택 조건의 리그 자료가 없습니다'));assert(get('teamcontent').innerHTML.includes('선택 조건의 경기가 없습니다'))});
test('direct team hash resolves exact club; unknown hash ignored',()=>{context.window.location.hash='#team=understat%3A150';events.hashchange();assert.strictEqual(get('teamselect').value,'understat:150');context.window.location.hash='#team=does-not-exist';events.hashchange();assert.strictEqual(get('teamselect').value,'understat:150')});
test('league table includes navigable team logos',()=>{nav[2].onclick();assert(get('standings').innerHTML.includes('data-team="understat:148"'));assert(get('standings').innerHTML.includes('승점 조정 미반영'))});
test('past comparison remains strictly before scheduled match',()=>{nav[0].onclick();assert(run('games(selected.home,null,selected.date).every(m=>m.date<selected.date)'));assert(get('trend').innerHTML.includes('<svg'))});
test('visitor screen contains no designer menu',()=>{assert(!html.includes('사이트 디자인 기준'));assert(!html.includes('DESIGN-SYSTEM'))});

test('team names share exact team route without nested links',()=>{let name=run('teamName("understat:83")');assert(name.includes('data-team="understat:83"'));assert(name.includes('>Arsenal</a>'));let combined=run('team("understat:83")');assert.strictEqual((combined.match(/<a /g)||[]).length,2);assert(!combined.match(/<a[^>]*>[^]*?<a[^>]*>[^]*?<\/a>[^]*?<\/a>/))});
test('team name click opens comprehensive overview',()=>{events.click({target:{closest(){return {dataset:{team:'understat:83'}}}},preventDefault(){}});assert.strictEqual(get('teamselect').value,'understat:83');assert.strictEqual(get('heading').textContent,'팀 종합 정보');const content=get('teamcontent').innerHTML;assert(content.includes('선택 경기 공격·수비'));assert(content.includes('최근 기대 득점'));assert(content.includes('다음 경기'));assert(content.includes('<details class="recorddetails">'));assert(!content.includes('<details class="recorddetails" open'))});
test('overview latest five and season win rate independently match data',()=>{get('season').value='2023/24';get('season').onchange();let ms=data.completed.filter(m=>m.season==='2023/24'&&(m.home==='understat:83'||m.away==='understat:83')).sort((a,b)=>a.date.localeCompare(b.date)||a.id.localeCompare(b.id));let wins=ms.filter(m=>m.home==='understat:83'?m.hg>m.ag:m.ag>m.hg).length;assert(get('teamcontent').innerHTML.includes((wins/ms.length*100).toFixed(1)+'%'));assert.strictEqual((get('teamcontent').innerHTML.match(/class="overviewdate">202[34]-/g)||[]).length,5)});
test('next fixtures are future scheduled records for selected team',()=>{let id='understat:83',ms=data.scheduled.filter(m=>(m.home===id||m.away===id)&&m.date>='2026-10-06').sort((a,b)=>a.date.localeCompare(b.date)||a.id.localeCompare(b.id)).slice(0,3);assert(ms.length>0);ms.forEach(m=>assert(get('teamcontent').innerHTML.includes(m.date)));assert(!run('teamOverview("understat:83",[])').includes('NaN'))});


test('team catalog contains league clubs and search narrows list',()=>{get('teamsearch').value='Arsenal';get('teamsearch').oninput();assert(get('teamcatalog').innerHTML.includes('Arsenal'));assert(!get('teamcatalog').innerHTML.includes('Liverpool'));get('teamsearch').value='';get('teamsearch').oninput()});
test('all 47 collected snapshot metrics exposed, category and text search work',()=>{run('openTeam("understat:83")');get('season').value='2023/24';get('season').onchange();assert.strictEqual(Object.keys(data.snapshots['understat:83|2023/24'].values).length,47);assert(get('snapcount').textContent.includes('47 / 47'));get('metricgroup').value='passing';get('metricgroup').onchange();assert(get('snapshotstats').innerHTML.includes('패스 성공률'));assert(!get('snapshotstats').innerHTML.includes('유효 슈팅'));get('metricsearch').value='PASS%';get('metricsearch').oninput();assert(get('snapcount').textContent.includes('1 / 47'));get('metricgroup').value='all';get('metricsearch').value='';run('renderSnapshot()')});
test('recent and custom-date filters change match summaries and detail totals',()=>{get('rangefilter').value='5';get('rangefilter').onchange();assert.strictEqual(run('selectedGames("understat:83").length'),5);get('rangefilter').value='custom';get('rangefilter').onchange();get('startdate').value='2023-08-01';get('enddate').value='2023-08-31';get('enddate').onchange();let ms=run('selectedGames("understat:83")');assert(ms.length>0);assert(ms.every(m=>m.date>='2023-08-01'&&m.date<='2023-08-31'));let expected=ms.reduce((s,m)=>s+data.match_detail['understat:83|'+m.id].npxg_for,0);assert(Math.abs(run('sumDetail("understat:83",selectedGames("understat:83"),"npxg_for")')-expected)<1e-8)});
test('season snapshot does not silently change under match filters',()=>{let expected=data.snapshots['understat:83|2023/24'].values.SH;assert.strictEqual(run('D.snapshots["understat:83|2023/24"].values.SH'),expected);const before=get('snapshotstats').innerHTML;get('venue').value='away';get('venue').onchange();assert.strictEqual(get('snapshotstats').innerHTML,before);assert(html.includes('期間')===false);assert(html.includes('기간/장소/결과 필터 미적용'))});
test('invalid dates are explicit and missing period is not zero statistics',()=>{get('startdate').value='2023-09-01';get('enddate').value='2023-08-01';get('enddate').onchange();assert(get('filtererror').textContent.includes('시작 날짜'));assert.strictEqual(run('selectedGames("understat:83").length'),0);assert.strictEqual(run('sumDetail("understat:83",[],"npxg_for")'),null);assert(!get('teamcontent').innerHTML.includes('NaN'))});
test('ratio aggregation and missing values preserve meaning',()=>{assert(run('detailedMatchStats("understat:83",[])').includes('—'));assert(run('detailedMatchStats("understat:83",games("understat:83","2023/24"))').includes('PPDA · 합산 비율'));assert.strictEqual(data.metric_meta['POSS%'].unit,'%');assert.strictEqual(data.metric_meta['PASS/M'].unit,'경기당')});


test('metric explanations are off by default with scoped metadata styles',()=>{assert.strictEqual(get('metricdetails').checked,false);assert(!get('team').classList.contains('show-metric-details'));assert(html.includes('#team .metric-note{display:none}'));assert(get('snapshotstats').innerHTML.includes('class="metric-note"'));assert(html.includes('기간/장소/결과 필터 미적용'))});
test('explanation toggle changes visibility without altering metrics',()=>{const before=get('snapshotstats').innerHTML;get('metricdetails').checked=true;get('metricdetails').onchange();assert(get('team').classList.contains('show-metric-details'));assert.strictEqual(get('snapshotstats').innerHTML,before);get('metricdetails').checked=false;get('metricdetails').onchange();assert(!get('team').classList.contains('show-metric-details'))});
test('explanation preference survives metric filtering and retains percentage units',()=>{get('metricdetails').checked=true;get('metricdetails').onchange();get('metricsearch').value='PASS%';get('metricsearch').oninput();assert(get('team').classList.contains('show-metric-details'));assert(get('metricdetails').checked);assert(get('snapshotstats').innerHTML.match(/<strong>[^<]+%<\/strong>/));get('metricdetails').checked=false;get('metricdetails').onchange()});


test('every snapshot metric has a Korean name and plain-language explanation',()=>{assert.strictEqual(Object.keys(data.metric_meta).length,47);Object.entries(data.metric_meta).forEach(([code,m])=>{assert(/[가-힣]/.test(m.label));assert.notStrictEqual(m.label,code);assert(m.description.length>5)});assert.strictEqual(data.metric_meta.A.label,'도움');assert.strictEqual(data.metric_meta['TKL-LM'].label,'최종 수비 태클');assert.strictEqual(data.metric_meta.PKC.label,'페널티킥 허용');assert(data.metric_meta.PKC.description.includes('실점 수가 아닙니다'))});
test('plain explanations render instead of code and original-total metadata',()=>{get('metricsearch').value='';get('metricgroup').value='all';run('renderSnapshot()');const cards=get('snapshotstats').innerHTML;assert(cards.includes('최종 수비 태클'));assert(cards.includes('페널티킥 허용'));assert(!cards.includes('TKL-LM'));assert(!cards.includes('PKC'));assert(!cards.includes('원본 합계'));assert(cards.includes(data.metric_meta.PKC.description))});
test('Korean names, explanation words and legacy codes remain searchable',()=>{for(const query of ['페널티킥 허용','PKC','실점 수가 아닙니다']){get('metricsearch').value=query;run('renderSnapshot()');assert(get('snapshotstats').innerHTML.includes('페널티킥 허용'));assert(get('snapcount').textContent.includes('1 / 47'))}get('metricsearch').value='TKL-LM';run('renderSnapshot()');assert(get('snapshotstats').innerHTML.includes('최종 수비 태클'))});

fs.writeFileSync(__dirname+'/logic-check.json',JSON.stringify({method:'Node VM with DOM stub; not real browser or image rendering',checks,failures:0},null,2));
console.log(checks+' checks passed.');
