from pathlib import Path
import json,re
p=Path(__file__).resolve().parents[1];d=p/'visualization-design-2026-10-06-v18'
assert not d.exists();d.mkdir()
texts={
 'ko':dict(title='AI 분석관에게 물어보세요',hint='저장된 기록을 분석합니다. 현재는 지원하는 표현을 해석하는 방식이며 AI 모델은 연결 전입니다.',placeholder='아스널 최근 10경기 득점과 기대 득점을 비교해 줘',submit='분석하기',examples=['아스널 최근 10경기 득점과 기대 득점을 비교해 줘','라리가 이번 시즌 경기당 기대 득점 순위','바르셀로나 홈 원정 성적 비교'],done='분석 완료 · 표와 차트를 확인해 주세요.',running='기록을 계산하고 있습니다.',empty='선택 조건에 해당하는 완료 경기 자료가 없습니다.',unsupported='지원하는 기록 분석 요청을 입력해 주세요. 아래 예시를 사용할 수 있습니다.',prediction='승리·무승부·패배 확률 도구는 아직 연결되지 않았습니다. 검증된 모델을 연결한 후 제공하겠습니다.',league='현재 지원하는 리그는 프리미어리그와 라리가입니다.',league_mismatch='선택한 리그와 팀이 다릅니다. 리그나 팀을 다시 지정해 주세요.',season='2023/24~2026/27 시즌 자료만 있습니다.',range='최근 경기 수는 1~38 사이로 지정해 주세요.',metric='이 요청의 지표는 현재 분석 도구에서 지원하지 않습니다. 득점·실점·기대 득점·기대 실점·승점·승률을 사용할 수 있습니다.',team='분석할 팀을 지정해 주세요.',full='시즌 전체',last='최근 {n}경기',split='홈·원정 각각',all='전체 장소',home='홈',away='원정',average='경기당 평균',total='합계',actual='실제 득점',through='자료 기준',local='저장된 완료 경기만 사용',series='초록 막대: 기대 득점 · 노랑 막대: 실제 득점',tableBelow='상세 수치는 아래 표',item='팀 / 경기',matches='경기 수',proof='계산 과정 보기',execution='실제 실행: 브라우저 JavaScript. AI 모델·SQL·Python 실행은 아직 연결되지 않았습니다.',formula='계산식',scopeNote='표시 조건만 적용합니다. 날짜 직접 지정·승무패 필터는 이 분석창에서 지원하지 않습니다. 최근 N경기는 선택 시즌 안에서 가져오며 홈·원정 비교에서는 각 장소별 N경기를 사용합니다. 승률은 과거 승리 비율이며 미래 승리 확률이 아닙니다.'),
 'en':dict(title='Ask the AI analyst',hint='Analyze stored records. Supported phrases are interpreted locally; an AI model is not connected yet.',placeholder='Compare Arsenal goals and xG in the last 10 matches',submit='Run analysis',examples=['Compare Arsenal goals and xG in the last 10 matches','LaLiga this season xG per match ranking','Compare Barcelona home and away'],done='Analysis complete · View the chart and table.',running='Calculating recorded matches.',empty='No completed matches meet these conditions.',unsupported='Enter a supported records request, or try an example below.',prediction='The win/draw/loss probability tool is not connected. It will require a validated prediction model.',league='Only Premier League and LaLiga records are supported.',league_mismatch='The club and league do not match. Specify another club or league.',season='Only 2023/24–2026/27 records are available.',range='Choose between 1 and 38 recent matches.',metric='This metric is not supported by the current tool. Try goals scored/conceded, xG/xGA, points or win rate.',team='Specify a club to analyze.',full='Full season',last='Last {n} matches',split='Home and away separately',all='All venues',home='Home',away='Away',average='Per-match average',total='Total',actual='Actual goals',through='Data through',local='Stored completed matches only',series='Green bars: expected goals · Yellow bars: actual goals',tableBelow='Exact values in the table below',item='Club / match',matches='Matches',proof='View calculation',execution='Executed in browser JavaScript. AI model, SQL and Python execution are not connected yet.',formula='Formula',scopeNote='Only displayed conditions apply. Custom dates and win/draw/loss filters are not supported here. Last N is within the selected season; venue comparisons use last N separately for each venue. Historical win rate is not future win probability.')
}
for lang,name in [('ko','index.html'),('en','index.en.html')]:
 s=(p/'visualization-design-2026-10-06-v17'/name).read_text(encoding='utf8');t=texts[lang]
 box='<section class="panel analyst-workbench" aria-labelledby="analysttitle"><h2 id="analysttitle">'+t['title']+'</h2><p class="muted">'+t['hint']+'</p><form id="analystform"><label for="analystquery">'+t['title']+'</label><div class="analystinput"><textarea id="analystquery" rows="2" maxlength="500" placeholder="'+t['placeholder']+'"></textarea><button type="submit">'+t['submit']+'</button></div></form><div id="analystexamples" class="analystexamples">'+''.join('<button type="button" data-id="'+q+'">'+q+'</button>' for q in t['examples'])+'</div><p id="analyststatus" role="status" aria-live="polite"></p><div id="analystresult"></div></section>'
 s=s.replace('<section id="matches">',box+'<section id="matches">')
 css='''
.analystinput{display:flex;gap:12px;align-items:stretch;margin-top:8px}.analystinput textarea{flex:1;min-width:0;font:inherit;padding:12px;border:2px solid #182b3b;background:#fff}.analystinput button{background:#ffe08a;color:#182b3b;font-weight:bold;border:2px solid #182b3b;padding:12px;min-height:44px}.analystexamples{display:flex;flex-wrap:wrap;gap:8px;margin-top:12px}.analystexamples button{font:inherit;white-space:normal;text-align:left;padding:10px;min-height:44px;max-width:100%}.analyst-workbench pre{white-space:pre-wrap;overflow-wrap:anywhere}.analystbar{display:grid;grid-template-columns:minmax(80px,1fr) minmax(50px,2fr) minmax(60px,1fr);gap:12px;align-items:center;margin:12px 0}.analystbar>span{overflow-wrap:anywhere}.analysttrack{height:10px;background:#e0e6da;margin:4px 0}.analysttrack span{display:block;height:100%;background:#21684c}.analysttrack.actual span{background:#a47700}.analystbar strong{text-align:right;font-size:14px}.analystchart{max-height:460px;overflow:auto;padding:4px}.analystlegend{font-size:14px}nav button,.teamname,.metric-trigger,select,.status,summary,.analystinput button{font-family:Galmuri11,Courier New,monospace}.analyst-workbench p,.analystexamples button,.analyst-workbench textarea{font-family:Arial,"Malgun Gothic",sans-serif;line-height:1.6}@media(max-width:650px){.analystinput{flex-direction:column}.analystbar{gap:6px;grid-template-columns:minmax(70px,1fr) minmax(40px,1.2fr) minmax(55px,1fr)}}
'''
 s=s.replace('</style></head>',css+'</style></head>')
 extra=(p/'analysis/record-engine.cjs').read_text(encoding='utf8')+'\nconst analystText='+json.dumps(t,ensure_ascii=False)+';const analystLanguage='+json.dumps(lang)+';\n'+(p/'analysis/workbench.js').read_text(encoding='utf8')
 if lang=='en':extra=re.sub('[가-힣]',lambda m:'\\u%04x'%ord(m[0]),extra)
 a,b=s.rsplit('</script>',1);s=a+extra+'\n</script>'+b
 (d/name).write_text(s,encoding='utf8');(p/name).write_text(s,encoding='utf8')
for name in ['check.cjs','check-en.cjs']:(d/name).write_bytes((p/'visualization-design-2026-10-06-v17'/name).read_bytes())
print('Built v18 bilingual record-analysis workbench and broader pixel typography.')
